### ISSUE TITLE
android: using gps app cannot resume from pause

### ISSUE THREAD

**Issue by pat1** [kivy/plyer#112]
if I use gps the app is stalled every times android go to sleep mode.
If I put gps.stop() in on_pause method the app is stalled too.

I/python  (29483): [INFO              ] [Android     ] Must go into sleep mode, check the app
I/python  (29483): >>>>>>>>> called on appication pause
I/python  (29483): going to save status
I/python  (29483): [INFO              ] [Android     ] App paused, now wait for resume.
I/WindowManager( 2038): Input event dispatching timed out sending to org.test.rmap/org.renpy.android.PythonActivity
E/ActivityManager( 2038): ANR in org.test.rmap:python (org.test.rmap/org.renpy.android.PythonActivity)
E/ActivityManager( 2038):   0.3% 26952/org.test.rmap:PythonService: 0.1% user + 0.2% kernel / faults: 54 minor
##

**Comment by trivedigaurav** [comment]
@pat1 I assume you are talking about the example gps app. I didn't implement on_resume for the app (http://kivy.org/docs/api-kivy.app.html#kivy.app.App.on_resume) so you can expect this behavior. This can be fixed.

I am not sure what exactly you mean when you say: "If I put gps.stop() in on_pause method the app is stalled too.".

**Comment by pat1** [comment]
I have my own app (not the example gps app). I have implemented on_stop on_pause on_resume.
The app works well; the app works if I use gps (gps.configure; gps.start; gps.stop). The app works if the phone go to sleep mode after I have called gps.stop. The app flash il I call gps.configure, gps.start and the the phone go to sleep. The app flash with or without gps.stop in on_pause method.
I can try to write a test case starting from gps example

**Comment by pat1** [comment]
I found a problem in my app; I can replicate the freeze in modified gps example:
https://gist.github.com/7f74e5158c49974fc557
how to reproduce:
activate gps by button
go with the phone to sleep mode
exit from sleep mode
the app is frozen

there is a bug in my main.py ; uncomment line 74 and all work well. 
So it's not a true plyer bug but you can take in account this condition.
Paolo

**Comment by kiok46** [comment]
@pat1  you gist link doesn't exist anymore. please update it for future references.
I think this issue could be closed?

**Comment by pat1** [comment]
new gist:
https://gist.github.com/pat1/f7022a065ae84cb1aacb1bc31dc181b3
