### ISSUE TITLE
Python4Android Hardware class

### ISSUE THREAD

**Issue by thegrymek** [kivy/plyer#127]
Hi,

I started to migrate hardware class from p4a to plyer. 

Here is current state of that: 
https://github.com/kivy/plyer/blob/dd649486f782a79ec6adcbdc5e555f3093cee138/examples/hardware/main.py

I have some questions about that:
1. Where put this class? As facade or just as platforms.android.hardware? Currently it sits in examples.
2. Some features that are implemented right now in plyer. 
- vibration
- magneticfield sensor
- accelerometer sensor

P4A Hardware class implements:  
- vibration
- show/hide keyboard
- dpi of screen
- wifi scanning
- state of connection
- accelerometer sensor
- orientation sensor
- magneticfield sensor

These sensors which are implemented right now I will not port, or I should? Vibration also is implemented in plyer.  
3. Orientation for android is finished in other pull request. 
 https://github.com/kivy/plyer/pull/43
 I havent notice any sensor for orientation there. I again glance on that and if needed I'll add.  
4. Hardware class should have his own example?
##

**Comment by thegrymek** [comment]
solution for this issue is here

https://github.com/kivy/plyer/pull/149

**Comment by dessant** [comment]
Issues should be closed only after the fix is merged.

**Comment by Julian-O** [comment]
The PR being asked about was closed in 2015.

Closing as stale.
