### ISSUE TITLE
Mail API not writing 'utf-8' characters correctly on mail application

### ISSUE THREAD

**Issue by trabak** [kivy/plyer#130]
I'm doing an application with kivy that is meant to send a email with the results of some calculations. The problem is that when i try to pass as content of the mail strings like 'ó' or 'ºC' is translated in the gmail application as 'Ã³' and 'ÂºC', respectively. Is this a bug?
##

**Comment by thegrymek** [comment]
Hi,

What platform it concerns?

best regards

**Comment by trabak** [comment]
Sorry, I forgot to mention it, this happens on Android.

Date: Wed, 20 May 2015 12:54:47 -0700

**Comment by Julian-O** [comment]
No action since 2015, and no-one else reporting a similar problem. Closing as stale.
