### ISSUE TITLE
Feature Request: Add adjustable tooltip text to Windows notification

### ISSUE THREAD

**Issue by brousch** [kivy/plyer#14]
Tooltip text is currently hard-coded to "Balloon tooltip" in windows notifications. Make this value adjustable by the user. Line ~42 in balloontip.py
##

**Comment by KeyWeeUsr** [comment]
Fixed in https://github.com/kivy/plyer/commit/1d7fb1fcc1d0171de35aede4060a54e3f8df5792 in #18, tooltip is `app_name`:

![image](https://user-images.githubusercontent.com/8825439/46922081-3dcb9980-d004-11e8-91f5-8379db54c767.png)
