### ISSUE TITLE
storage path support

### ISSUE THREAD

**Issue by kived** [kivy/plyer#152]
We should have an API for cross-platform access to storage paths, like a base path which maps to ~ on desktop and Environment.getExternalStorageDirectory() on Android, and maybe media-type paths like Enviroment.getExternalStoragePublicDirectory(type) for Android which would map to the appropriate folders (i.e. `~/Pictures` on Linux or `~\My Pictures` on Windows).
##

**Comment by malverick** [comment]
Achieved using #342 :)

**Comment by KeyWeeUsr** [comment]
Closed by #342.
