### ISSUE TITLE
Notification's Click Behavior

### ISSUE THREAD

**Issue by wpbloger** [kivy/plyer#154]
Hello.
I need to go back to the application when you click on the notification.
To implement the notification, write that plyer.notifikation gently used, but I did not find ways to set a click event to the notification
Is there any way to do this?
##

**Comment by linuxrootok** [comment]
`context = PythonActivity.mActivity
        pending_intent = PendingIntent.getActivity(context, 0, Intent(context, context.getClass()).addFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP), 0)


        noti.addAction(0, String("Start"), pending_intent)
        noti = noti.build()
        notification_service.notify(0, noti)
        `

**Comment by KeyWeeUsr** [comment]
Haven't tried, but it seems to me that the @linuxrootok's code will work. Also, if it works for you, feel free to submit a Pull Request with the change, so that it's included in plyer by default :)

**Comment by linuxrootok** [comment]
I had done this,it works well.

**Comment by AndreMiras** [comment]
Thanks guys, I'm using it for one of my apps and it works great. I've made a pull request https://github.com/kivy/plyer/pull/422
