### ISSUE TITLE
Example app for Camera facade

### ISSUE THREAD

**Issue by brousch** [kivy/plyer#16]
We need a camera example app
##

**Comment by kamathln** [comment]
@trivedigaurav Are you in India? I get this 
![screenshot](https://cloud.githubusercontent.com/assets/241043/17829754/846e952a-66d6-11e6-9bbf-3d242a1d3710.png)

**Comment by jchome** [comment]
Hello, Now, source files are available again on this URL:
http://julien.coron.free.fr/raw/takepicture-plyer/

**Comment by KeyWeeUsr** [comment]
Closed by #41
