### ISSUE TITLE
Plyer needs a mechanism to retrieve an Activity from different places

### ISSUE THREAD

**Issue by inclement** [kivy/plyer#164]
Currently the Android facades use org.renpy.android.PythonActivity.mActivity, but plyer doesn't need to be bound to kivy's pygame mechanism like this. I'm not sure how to make it customisable in a nice way though, so opening this issue both to register the issue and to see if anyone has suggestions.'

Edit: For instance, with Kivy + SDL2 it will probably be org.kivy.android.PythonActivity.mActivity
##

**Comment by KavenC** [comment]
Hi, I encounter this issue when using plyer/android with buildozer android_new target. I haven't completely understand the problem but it seems that `buildozer android` needs org.renpy.android.PythonActivity and `buildozer android_new` needs org.kivy.android.PythonActivity.

So like you say, there should be better way to retrieve correct activity. Just leaves a comment here to let people know there will be a problem if using buildozer + plyer.

**Comment by Julian-O** [comment]
No suggestions after 8 years.

Closing as stale.
