### ISSUE TITLE
more example code to the docs

### ISSUE THREAD

**Issue by buhtz** [kivy/plyer#166]
Please add more example code to the docs.
e.g. I couldn't find out how to use `speak()`. This won't work 'from plyer.facades.tts import speak'.

Know I know how to use it because of example code from the gps module.

I would suggest to remove the example code from there current place and create a own section in the docs for example code.
##

**Comment by kiok46** [comment]
Hi!
You can find the examples and usage in `plyer/examples` and each individual feature file in `plyer/facades/`.

@akshayaurora  please close the issue.
