### ISSUE TITLE
unicode broken in notifications on windows 8.

### ISSUE THREAD

**Issue by tshirtman** [kivy/plyer#17]
Opening a notifications on windows 8.1 works, but unicode characters ("éàùç" and their friends) are displayed improperly, probably using a bad encoding (i would suspect a latin-1 or similar encoding).

(that's running the provided example)
##

**Comment by KeyWeeUsr** [comment]
Can't reproduce on Windows 8.1 with [`9dd168d`](https://github.com/kivy/plyer/blob/9dd168de506879f41896cd821e1464672b17b0e3/plyer/platforms/win/libs/balloontip.py) and with latest master [`32f8e2c`](https://github.com/kivy/plyer/blob/32f8e2ca7858fe01917ff7361822796b12baf391/plyer/platforms/win/libs/balloontip.py) on Py2 + Py3.
