### ISSUE TITLE
Something wrong with encoding in AndroidNotification

### ISSUE THREAD

**Issue by Hukuta** [kivy/plyer#175]
```
def notify(title, message):
    return AndroidNotification().notify(title=title, message=message)

notify(u'Vk Service', u'Нет новых сообщений')
```

and i see this notification:

![s51101-014425](https://cloud.githubusercontent.com/assets/3100053/10866530/fa84a610-803a-11e5-85cf-69bc10c76b8a.jpg)

but next works without such problems:

```
class MyApp(App):
    def build(self):
        return Label(text=u'Привет')
```

![2015-10-31 23 54 50](https://cloud.githubusercontent.com/assets/3100053/10866542/a5a3b892-803b-11e5-9b0a-1c2ca5240970.jpg)

What can I do to localize notifications? 
##

**Comment by Kovak** [comment]
Make sure the encoding on your supplied strings is utf-8 as that is what plyer is expecting.

**Comment by Hukuta** [comment]
I'm using unicode strings ( u'...' )
Look at method _notify in [AndroidNotification](https://github.com/kivy/plyer/blob/master/plyer/platforms/android/notification.py) class, 
I see ".encode('utf-8')" there: 

    def _notify(self, **kwargs):
        icon = getattr(Drawable, kwargs.get('icon_android', 'icon'))
        noti = NotificationBuilder(activity)
        noti.setContentTitle(AndroidString(
            kwargs.get('title').encode('utf-8')))
        noti.setContentText(AndroidString(
            kwargs.get('message').encode('utf-8')))
        noti.setSmallIcon(icon)
        noti.setAutoCancel(True)

        if SDK_INT >= 16:
            noti = noti.build()
        else:
            noti = noti.getNotification()

        self._get_notification_service().notify(0, noti)

double "encode" leads to exception:

![selection_140](https://cloud.githubusercontent.com/assets/3100053/10867898/180dd916-8083-11e5-9586-57bf8eb76c22.png)

**Comment by Hukuta** [comment]
I made [demo app](https://github.com/Hukuta/kivy-plyer-issue-175) to demonstrate problem, may be this will help to solve it.

**Comment by IvanTheFirst** [comment]
I had problem with sms example, maybe this is the same? Try this:
unicode(str('я').strip(codecs.BOM_UTF8), 'utf-8')

this will clean utf8 header from the Python string

**Comment by KeyWeeUsr** [comment]
Right now I could display not only cyrillic characters, but even emoji characters in the notification. Please check with either the latest stable (`1.3.2`) or even `master` branch. New release will come soon.
