### ISSUE TITLE
Windows microphone support

### ISSUE THREAD

**Issue by MRFaria** [kivy/plyer#179]
I want to try and add windows microphone recording support to kivy/plyer and was wondering if there is currently much interest in this and if so, if I should be using the windows api directly or If I can just use something like the PyAudio library to interface to windows.
##

**Comment by tshirtman** [comment]
as a datapoint, there is already a PR that uses PyAudio (https://github.com/kivy/plyer/pull/150), for linux playback, if it makes things easier, i guess it can be used on the platforms where it's available.

**Comment by KeyWeeUsr** [comment]
Closed by #489.
