### ISSUE TITLE
GPS crashes on ios simulators > iPhone 5 (EXC_i386_GPFLT)

### ISSUE THREAD

**Issue by doratoa** [kivy/plyer#186]
Sorry if it's possibly pyobjus issue, but anyway result is that I can't use GPS for iOS which is critical for my app.
Regrettable, but I can't operatively test app on real device since only one I have access to, ipad mini, unable to run app at all (btw it also breaks with EXC_BAD_ACCESS errors in different place)
But app works just fine with simulators like iphone 5 and 4s receiving coords on  mock locations.

I was able to enable GPS support for earlier iphone simulators same way as described in one of issues here (and I think it should be added to docs! Which I'll be glad to do.)
But on more recent devices xcode stops pointing at ffi64_x86_64.c

> ffi_call_unix64 (stack, cif->bytes + sizeof (struct register_args),
>                    cif->flags, rvalue, fn, ssecount);

with message: EXC_BAD_ACCESS (code=EXC_i386_GPFLT)

Log just before the break: (pyobjus debug=1)

> [DEBUG] Parsing property attributes --> Td,R,N 
> [DEBUG] <-- return object <plyer.platforms.ios.gps.CLLocation object at 0x7f8d251466c0> 
> [DEBUG] -------------------------------------------------------------------------------- 
> [DEBUG] **call**() coordinate 0x10ed0a8f0 0x7f8d2520e130 
> [DEBUG] --> want to call coordinate () 
> [DEBUG] --> return def is ('{?=dd}', '16', None) 
> [DEBUG] --> args def is [('@', '0', None), (':', '8', None)] 
> [DEBUG]  - [0] class instance 0x7f8d2520e130 
> [DEBUG]  - selector is 0x11b259de2 
> [DEBUG] -------------------------------------------------------------------------------- 
> [DEBUG] signature ensure_method --> coordinate ('{?=dd}', '16', None) 
> [DEBUG] pre-zip signature: [('@', '0', None), (':', '8', None)] 
> [DEBUG] array signature zip: [('@', '0', None), (':', '8', None)] 
> [DEBUG] input for type_encoding_to_ffitype(type_encoding={?=dd}, str_in_union=False) 
> [DEBUG] rest list --> ['d', 'd'] 
> [DEBUG] input for type_encoding_to_ffitype(type_encoding=d, str_in_union=False) 
> [DEBUG] input for type_encoding_to_ffitype(type_encoding=d, str_in_union=False) 
> [DEBUG] argument ==> ('@', '0', None) 2 
> [DEBUG] input for type_encoding_to_ffitype(type_encoding=@, str_in_union=False) 
> [DEBUG] argument ==> (':', '8', None) 2 
> [DEBUG] input for type_encoding_to_ffitype(type_encoding=:, str_in_union=False) 
> [DEBUG] --- really call coordinate with args () (signature is [('@', '0', None), (':', '8', None)]) 
> [DEBUG]    > 0: 140244187158080 
> [DEBUG]    > 1: 140244187158088 
> (lldb) 

Full log if needed: http://paste.opensuse.org/50494408
Thanks for any support!
##

**Comment by doratoa** [comment]
After some testing, and with kind help of **kived** I could check that:
1. App works on a few newer physical devices: iphones: 5s, 6s; ipads: mini 2 (Model A1490), Air 2 (Model A1566)
2. App breaks at *plyer.platform.ios.gps.locationManager_didUpdateLocations_*
The idea was is that location could be nil, but this debug prints showed different:
```
    @protocol('CLLocationManagerDelegate')
    def locationManager_didUpdateLocations_(self, manager, locations):
        location = manager.location
        print("*[DEBUG] plyer.platforms.ios.gps.locationManager_didUpdateLocations_()")
        print(self.activated) # set to True on _start() / False on _stop() just in case 
        print("plyer: location is type '{1}' <{0}>".format(location, type(location))) 
        print('speed {0}'.format(location.speed))
        print('coordinate {0} {1}'.format(location.coordinate.a, location.coordinate.b))
        print('calling self.on_location')
        self.on_location(
            lat=location.coordinate.a,
            lon=location.coordinate.b,
            speed=location.speed,
            bearing=location.course,
            altitude=location.altitude)
```
Output around stop:
```
*[DEBUG] plyer.platforms.ios.gps._start()
*[DEBUG] plyer.platforms.ios.gps.locationManager_didUpdateLocations_()
True
plyer: location is type '<class 'plyer.platforms.ios.gps.CLLocation'>' <<plyer.platforms.ios.gps.CLLocation object at 0x7fe7384d7c90>>
speed -1.0
```
You can see I can get `location.speed` but any access to `location.coordinate` results in error described (even `if location.coordinate:`)
I didn't checked other attributes of location.

If it matters here version info of Mac system:
Xcode 7.2.1
OS X El Capitan 10.11.4 Public Beta 5 and 6
Simulator iOS 9.2  # at least real iPhone 6s used for testing is also 9.2
Kivy 1.9.1
plyer 1.2.4 and 1.2.5 dev
_Just saw new update to Xcode 7.3, I'll check it later._

**Comment by doratoa** [comment]
Crashes stopped with Xcode 8 iOS 9.3/10.0, but GPS behaviour is still strange (Some simulators have "usage" popup, some don't, some have GPS working, some just silently give no data. No patterns found yet.)

**Comment by Julian-O** [comment]
Crashes seem to be solved. If other behaviour patterns are determined, please raise a separate Issue.
