### ISSUE TITLE
Camera on android doesn't return to app

### ISSUE THREAD

**Issue by redfast00** [kivy/plyer#200]
When I tried to use the code in https://github.com/kivy/plyer/pull/41/files , the camera opened fine. When I took a picture, I got a screen with a checkmark (like in the picture below)
![t](https://cloud.githubusercontent.com/assets/10746993/14768350/30d2de14-0a40-11e6-8702-79625b30d7ae.jpg)
When I pressed the checkmark, it doesn't do anything. If I return to the app by pressing the cross, I get a popup saying that it was unable to save the image. I am on CyanogenMod 13.0 (Android 6.0 aka Marshmallow) on a OnePlus Two.

**Comment by kiok46** [comment]
@redfast00  Could you please post the logs?

**Comment by redfast00** [comment]
This is because of a bug in #41 (which saves to `os.getcwd()`). This is fixed by #205 (which saves to `app.user_data_dir`).
