### ISSUE TITLE
accelerometer on Android with Kivy Launcher 1.9.0 not working

### ISSUE THREAD

**Issue by MichaelPython** [kivy/plyer#206]
i am using Kivy Launcher 1.9.0 to run my app.
my app hangs with this code:
from plyer import accelerometer; accelerometer.enable(); val=accelerometer.acceleration[:]; accelerometer.disable()
but other facades such as vibrator works.
i tried it on 2 android phones, one with Android 4.2 , the other Android 4.4, same result.
how can i access the accelerometer?
##

**Comment by kiok46** [comment]
Duplicate of kivy/kivy#4308
Please close this issue.
