### ISSUE TITLE
Camera Support for iOS

### ISSUE THREAD

**Issue by brousch** [kivy/plyer#21]
Add support for the camera facade to iOS
##

**Comment by sontek** [comment]
Any update on camera support?

**Comment by vccabral** [comment]
I need this feature in an app I am creating. If anyone has any interest I can fund the bounty.

**Comment by gorgonaut04** [comment]
This would be HUGE! I basically need to figure this out, or find a new platform for the iOS version of my app. Shame, because the Android version is basically done :(

**Comment by skwaugh** [comment]
@bluecollar Hey - would you mind if I took a look at your project?

**Comment by gorgonaut04** [comment]
Seconded...any hints as to how to get the camera going on iOS would be immensely helpful

**Comment by gorgonaut04** [comment]
Is there a technical barrier to achieving this? Any new developments?

**Comment by KeyWeeUsr** [comment]
Closed by #167.
