### ISSUE TITLE
audio: JVM exception occurred: setAudioSource failed.

### ISSUE THREAD

**Issue by nickyspag** [kivy/plyer#210]
Hi

I'm getting the error below when trying to record audio using plyer.

I'm using kivy-remote-shell and have added RECORD_AUDIO to android permissions buildozer.spec

This is what I'm trying:

```
from plyer import audio
audio.file_path = 'test.3gp'
audio.start()
```

I get this:

```
  File "jnius/jnius_utils.pxi", line 93, in jnius.jnius.check_exception (jnius/jnius.c:3746)
JavaException: JVM exception occurred: setAudioSource failed.
```

Version is '1.2.5dev'

Am I using it wrong? 

Thank you kindly.
##

**Comment by KeyWeeUsr** [comment]
Tested with the latest `master` and it works properly on Android Oreo. Try updating to the latest versions.
