### ISSUE TITLE
uniqueid.id raises exception on Windows

### ISSUE THREAD

**Issue by WillDHB** [kivy/plyer#212]
Using plyer.uniqueid.id on Windows 10 raises the following exception:

C:\Python27\lib\site-packages\plyer-1.2.1-py2.7.egg\plyer\platforms\win\uniqueid.pyc in _get_uid(self)
     14         hKey = regedit.OpenKey(regedit.HKEY_LOCAL_MACHINE,
     15             r"SOFTWARE\\Microsoft\\Cryptography")
---> 16         value, _ = regedit.QueryValueEx(hKey, "MachineGuid")
     17         return value
     18

WindowsError: [Error 2] The system cannot find the file specified

**Comment by dessant** [comment]
This should be fixed in https://github.com/kivy/plyer/commit/fcb84fd748c48a3d85383bf1879ac283acc593ad.

```
pip install -U https://github.com/kivy/plyer/archive/master.zip
```
