### ISSUE TITLE
GPS example only updating location once

### ISSUE THREAD

**Issue by frmdstryr** [kivy/plyer#217]
On Android the GPS example only updates once shortly after started. In order to get another update it must be stopped and started again. Can someone else please confirm?

**Comment by kiok46** [comment]
@frmdstryr  Nope, that's not the case. The update depends upon 2 parameters.

-     minTime : minimum time interval between location updates, in milliseconds.
-     minDistance : minimum distance between location updates, in meters.

Right now these values are manually set to be 1000 milliseconds and 1 meter respectively.

**Comment by kiok46** [comment]
@frmdstryr Use #218 to configure them as per your need.
