### ISSUE TITLE
Drag-and-drop: originate in Kivy, drop in some external app

### ISSUE THREAD

**Issue by janssen** [kivy/plyer#228]
You should be able to initiate a drag from a Kivy widget, which would put a string or an image or a filename into the native drag-and-drop framework, to be dropped on some external application.  Drag stuff _out_ of Kivy.
##

**Comment by kiok46** [comment]
@janssen  This issue should be opened in kivy or maybe a flower in kivy-garden?
But as plyer is **independent** of kivy, we can not(should not) design such functionality only for it.`

**Comment by dessant** [comment]
Duplicate of https://github.com/kivy/kivy/issues/3557.
