### ISSUE TITLE
New PyPi release please, to fix static jfieldID not valid for class java.lang.Class<org.renpy.android.PythonActivity>

### ISSUE THREAD

**Issue by cidermole** [kivy/plyer#229]
Would somebody please release a new plyer to https://pypi.python.org? `pip install` gets `plyer-1.2.4` which is not compatible with the current kivy, because it triggers this bug, which has been fixed:

see https://github.com/kivy/python-for-android/issues/686#issuecomment-244339929
##

**Comment by dessant** [comment]
It will happen eventually, until then you can install from master:
```
pip install https://github.com/kivy/plyer/archive/master.zip
```
