### ISSUE TITLE
Weird GPS issue on iOS 10

### ISSUE THREAD

**Issue by gorgonaut04** [kivy/plyer#240]
On iOS 10 devices and simulators, the lat/lon are not available when the delegate function / callback locationManager_didUpdateLocation_()  is called. The data structure is inexplicably incorrect. "manager.location" is of type CLLocation (correct), but when trying to access manager.location.coordinate, of type CLLocationCoordinate2D on iOS 8/9, I get the error "not enough parameters for coordinate" on iOS 10. What?? Should this be a plyer or pyobjus issue? I can't understand how this could be happening just in kivy!

My current workaround is to get the debugprint member from manager.location, and parse that string for the lat/lon and accuracy. It works, but the docs claim this is deprecated...

**Comment by gorgonaut04** [comment]
Just to confirm, everything was working fine in iOS 8 & 9. The only thing that changed was that users updated their phones to iOS 10 and stopped getting GPS position updates.

**Comment by doratoa** [comment]
Regrettably I confirm the problem, my friend have just updated to iOS 10 and GPS stopped working. Can't verify since I don't have real devices, but Simulators don't seem to use mock locations too.
@gorgonaut04 do you mind sharing code for your workaround while issue is not solved?

**Comment by gorgonaut04** [comment]
I've only parsed out lat/lon and accuracy, so if you need speed, bearing, or altitude, you'll need to parse them out as well. Make sure you get the latest kivy ios, or else the lack of prints/logging on iOS 10 without that fix will make things very difficult!

```python
'''
iOS GPS
-----------
'''
    @protocol('CLLocationManagerDelegate')
    def locationManager_didUpdateLocations_(self, manager, locations):
        location = manager.location
        description = location.description.UTF8String()
        lat, lon = [float(coord) for coord in description.split('<')[-1].split('>')[0].split(',')]
        acc = float(description.split(' +/- ')[-1].split('m ')[0])
 
        self.on_location(lat=lat, lon=lon, accuracy=acc)
```

**Comment by doratoa** [comment]
Thank you, @gorgonaut04 
We have a live app in AppStore and it was very bad news for us if GPS breaks on iOS 10 update.
Have to patch it asap, and i don't really have experience with Pyobjus yet. But I'll try to figure out something after.

**Comment by gorgonaut04** [comment]
Same here! We faced this a month or so ago and I literally pulled an
all-nighter trying to fight through the combined lack lack of prints/logs
and this problem. Eventually cobbled together my own print statement using
NSLog, via pyobjus

**Comment by doratoa** [comment]
Thanks, you workaround seems to work pretty fine, simulators for both 9.3 and 10.0 handle mock location OK too. I'll try to if not get to the core of original problem myself, then pointing community attention to it.

**Comment by kennedyshead** [comment]
+1 for this issue!

**Comment by zoltan-fedor** [comment]
+1

**Comment by keavin7** [comment]
Heyo! It seems like this error is occuring deeper in pyobjus but I expanded on the string parsing hack above to add accuracy speed course and altitude. We should push something out soon. GPS is critical for many apps and we don't want the kivy to suffer a lapse. Let me know if i can help here :)

```
    @protocol('CLLocationManagerDelegate')
    def locationManager_didUpdateLocations_(self, manager, locations):
        location = manager.location

        description = location.description.UTF8String()
        lat, lon = [float(coord) for coord in description.split('<')[-1].split('>')[0].split(',')]
        acc = float(description.split(' +/- ')[-1].split('m ')[0])

        speed=location.speed
        altitude=location.altitude
        course=location.course

        self.on_location(
            lat=lat,
            lon=lon,
            speed=speed,
            bearing=course,
            altitude=altitude,
            accuracy = acc)
```

**Comment by glins97** [comment]
Stuck on the same boat right now. I'm quite new to all this and could not figure out how to make the code above work. 

Any hints?

**Comment by doratoa** [comment]
@glins97 have you patched your ios gps with @gorgonaut04 code? My App still uses it

**Comment by glins97** [comment]
Yeah, it works!
For those that might be unsure how to proceed, all you have to do is replace plyer/platforms/ios/gps.py with the function above.
Cheers.

**Comment by tshirtman** [comment]
not an ios user myself, but seems like this code should be made into a pull request to benefit more users.

thanks.

**Comment by HourGlss** [comment]
is this fixed?

**Comment by Dirk-Sandberg** [comment]
@glins97 Where exactly is the gps.py file? I have found 3 gps.py files, and none of them seem to work when I insert the code above - it appears that the files I found aren't executing at all (i put some print statements in). The three files I found were

/foo/bar/kivy-ios/build/plyer/x86_64/plyer-master/build/lib/plyer/platforms/ios/gps.py

/foo/bar/kivy-ios/build/plyer/x86_64/plyer-master/iosbuild/lib/python2.7/site-packages/plyer/platforms/ios/gps.py

foo/bar/kivy-ios/build/plyer/x86_64/plyer-master/plyer/platforms/ios/gps.py

I tried to update my project with `./toolchain.py update project-name` as well

**Comment by gorgonaut04** [comment]
You have to make sure you delete any "gps.pyo" files in order to force the
.py file to be re-compiled. That should help you narrow down the critical
file (I apologize, it's been a couple years, so I don't remember which file
is the critical one to edit.)
