### ISSUE TITLE
Send SMS feature not working

### ISSUE THREAD

**Issue by malverick** [kivy/plyer#261]
When I press the 'Send Sms' button then I receive the warning that 'charges may apply' and after agreeing to the warning nothing happens.

**Comment by malverick** [comment]
I am working on the fixing the issue and will send the pr once done.

**Comment by akshayaurora** [comment]
did you check if you gave the app the appropriate permissions? Just tested with 10 + devices in a workshop, it works.

**Comment by shahzadakram67** [comment]
When I press the 'Send Sms' button then my app crashes why is this so,,???
