### ISSUE TITLE
GPS android crash on launch

### ISSUE THREAD

**Issue by jlongwe** [kivy/plyer#288]
When i try run the exact same GPS example from the examples folder, it compiles successfully but once i launch the application on my android version 5 device, it crashes. I have been struggling with this for a while now and I desperately need help with it. I am using python 2.7 with buildozer on Linux Ubuntu VM. Logcat attached.
removed logcat.txt
[main.txt](https://github.com/kivy/plyer/files/785687/main.txt) ran as main.py
[buildozer.txt](https://github.com/kivy/plyer/files/785688/buildozer.txt) ran as buildozer.spec

**Comment by malverick** [comment]
Hi @jlongwe , after you posted this issue, I made an apk for gps example and it's running fine for me.
I am not able to see your logcat.txt file in correct format. I would suggest you to paste your logcat in gist and then share the link. I can't help you without seeing the logs of your app.

**Comment by jlongwe** [comment]
Hi @malverick please find the logcat contents at https://gist.github.com/jlongwe/7a006cc5f59b70680c1963c96691c981

**Comment by malverick** [comment]
@jlongwe you have not filtered your logcat results.

1. Connect your device
2. Open terminal
3. Run `adb -d logcat <your package name>:V *:S` 

These are the logs related only to your gps apk.
Please share those logs.

**Comment by jlongwe** [comment]
Hi @malverick thanks. I couldn't get that to work on my Ubuntu system as it returned nothing. But i managed to filter them with
**adb logcat | grep "python"**: https://gist.github.com/jlongwe/d69fd22332cd9dc37d6d67c303b679de
**adb logcat | grep "gpsexample"**: https://gist.github.com/jlongwe/7a006cc5f59b70680c1963c96691c981

**Comment by jlongwe** [comment]
Looked like an indentation issue in my code. Resolved

**Comment by phunsukwangdu** [comment]
@jlongwe  adding to malverick views,you can use android studio logcat monitor with your kivy app.The plus point is that it pin points the error with different colour and you have various filter options.
