### ISSUE TITLE
Accelerometer not working on linux

### ISSUE THREAD

**Issue by bhaveshAn** [kivy/plyer#327]
![accelerometer not working](https://cloud.githubusercontent.com/assets/22936570/24830197/7e52b360-1c70-11e7-915e-04c420e101e0.png)

**Comment by malverick** [comment]
@bhaveshAn I tried the same example and its working fine on my system.
Ubuntu 16.04 LTS
plyer 1.3.1.dev0

**Comment by bhaveshAn** [comment]
@malverick  Its still not working for me. Even when i import `glob` externally to check its availability.
How it could happen Kindly send any screenshot of the working.
```
>>>from plyer import accelerometer
>>> accelerometer.acceleration
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "plyer/utils.py", line 103, in __getattribute__
    return getattr(object.__getattribute__(self, '_obj'), name)
  File "plyer/facades/accelerometer.py", line 44, in acceleration
    return self.get_acceleration()
  File "plyer/facades/accelerometer.py", line 60, in get_acceleration
    return self._get_acceleration()
  File "plyer/platforms/linux/accelerometer.py", line 24, in _get_acceleration
    raise Exception('Could not enable accelerometer!')
Exception: Could not enable accelerometer!
>>> import glob
>>> import glob
>>> accelerometer.acceleration
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "plyer/utils.py", line 103, in __getattribute__
    return getattr(object.__getattribute__(self, '_obj'), name)
  File "plyer/facades/accelerometer.py", line 44, in acceleration
    return self.get_acceleration()
  File "plyer/facades/accelerometer.py", line 60, in get_acceleration
    return self._get_acceleration()
  File "plyer/platforms/linux/accelerometer.py", line 24, in _get_acceleration
    raise Exception('Could not enable accelerometer!')
Exception: Could not enable accelerometer!

```

**Comment by bhaveshAn** [comment]
@KeyWeeUsr I am using Ubuntu 16.04 LTS on Dell Vostro 3558.

**Comment by KeyWeeUsr** [comment]
@bhaveshAn I don't see any support for an accelerometer in the [specifications](https://us.hardware.info/product/340314/dell-vostro-3558-8805/specifications), but let's wait for @malverick so that we're sure he has one. 😋

**Comment by malverick** [comment]
I have HP Pavilion 15-ab219tx. I cannot find any page stating that this model has accelerometer but my laptop has a feature of HDD protection which switches off hard drive when `acceleration=g` to protect hard drive and data in it.

**Comment by KeyWeeUsr** [comment]
Yep, it does - somewhere in manual you'll find it too and it's [probably in all](http://h10032.www1.hp.com/ctg/Manual/c03939658.pdf) HP Pavilion 15 models from such generally named manual. Nice feature!
