### ISSUE TITLE
Notification not working on Windows

### ISSUE THREAD

**Issue by EngineerCoding** [kivy/plyer#333]
Currently I am using the plyer API to send notifications to windows/linux/etc, however on windows this will not work due to an error. I have not tested this on other OS's, however I'd like a multiplatform solution since I might use my program elsewhere. 

I am currently using windows 10 and the latest plyer installed by pip (python 3.6.1), and use the following code plus relevant stack trace:

```python
plyer.notification.notify("Removed {} from downloads".format(path), "Hash: " + data[self.directory][path]["hash"])

  File "C:\Users\NotRelevant\AppData\Local\Programs\Python\Python36\lib\site-packages\plyer\platforms\win\libs\balloontip.py", line 145, in balloon_tip
    WindowsBalloonTip(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'ticker'
```

As you can see I am not using the ticker argument, so something went wrong in the internal API.

**Comment by AlvarBer** [comment]
Can confirm this issue happens even if you set the ticker keyword.

```
>>> notification(title='title', message='m', ticker='r')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'Proxy' object is not callable
```

Windows 8.1, python 3.5.3

**Comment by KeyWeeUsr** [comment]
@AlvarBer It works just fine with the latest commit - https://github.com/kivy/plyer/commit/0007a63f9571be54dfeeeb2830faa2162e0ef99f

```
>>> from plyer import notification as n
>>> n.notify(title='title', message='m', ticker='r')
```

**Comment by EngineerCoding** [comment]
@KeyWeeUsr By looking at the code, the balloontip.py which is getting called, it shows no ticker argument as my exception suggests. I can ugly fix it by adding the argument and not doing anything with it, however I am sure you have a much more cleaner solution.


As my program is not going to be distributed, it does not matter that much as I can fix it ugly myself, however it is still an error. Looking at other implementations the **kwargs argument is used instead of all the actual arguments in that method where it errors, and would suggest that fix at least.


Maybe I will make a simple pull request for the latter, but time is scarce at the moment ;)

**Comment by KeyWeeUsr** [comment]
I wrote since X commit, which means your installation has to have that commit. PyPI wouldn't, because that's the stable version of plyer. You can install it with:

    pip install -I https://github.com/kivy/plyer/zipball/master

About the arguments, I put there `**kwargs` because I have no knowledge about `ticker` being available on Windows, therefore only the explicitly required args will be used and whatever else will be collected into `kwargs` dictionary.

**Comment by Swardu** [comment]
I'm having the same issue, using the pip version. Windows 10, Python 3.6.2.
```
from plyer import notification as n
n.notify(title='title', message='m', ticker='r')

```

**Comment by Plbhattad7** [comment]
Even I had this problem, so what I did is:
Step 1:
`pip install plyer` (in your terminal)
Step 2:
`import plyer` (in your python code)
Step 3:
`plyer.facades.notification.Notification.notify()`
Step 4: 
You can write your functions...

**Comment by Shuvadip-Ghosh** [comment]
I am also having a problem
My code
`from plyer import notification
notification.notify(
            title = "Drink Water",
            message="Sir you havent Drank water for about 1 hour" ,
            timeout=2
            )`
My error is
Traceback (most recent call last):
  File "D:\Python Programs\desktop-notifier\main.pyw", line 15, in <module>
    notification()
  File "D:\Python Programs\desktop-notifier\main.pyw", line 7, in notification
    notification.Notification.notify(
AttributeError: 'function' object has no attribute 'Notification'

Please can anyone help to solve this.
