### ISSUE TITLE
Fix

### ISSUE THREAD

**Issue by kuzeyron** [kivy/plyer#358]
from os import environ
from jnius import autoclass

ANDROID_VERSION = autoclass('android.os.Build$VERSION')
SDK_INT = ANDROID_VERSION.SDK_INT
from android import config
try:
	#ns = config.JAVA_NAMESPACE
	if config.JAVA_NAMESPACE == 'org.kivy.android':
		ns = 'org.kivy.android'
	else:
		ns = 'org.renpy.android'
except (ImportError, AttributeError):
	ns = 'org.kivy.android'

if 'PYTHON_SERVICE_ARGUMENT' in environ:
    PythonService = autoclass(ns + '.PythonService')
    activity = PythonService.mService
else:
    PythonActivity = autoclass(ns + '.PythonActivity')
    activity = PythonActivity.mActivity

Now working with org.renpy and org.kivy.
Needs to be set in the requirement: plyer,android
I'm a total noob when it comes to Github. Please help me get this right. No more peoples to suffer!

**Comment by Julian-O** [comment]
Can someone please explain what this code is supposed to do, and whether it is still relevant?
