### ISSUE TITLE
plyer.notify.notification doesn't show ticker in Android

### ISSUE THREAD

**Issue by jcrmatos** [kivy/plyer#378]
Hello,

The 1st issue occurs on my Windows 7 Pro SP1 x64 where I'm using Python 3.5.4 x32 and Kivy 1.10.0.
When I use this instruction
`notification.notify('Local error', 'test message')`
plyer complains with the following error
```
 Exception in thread Thread-2:
 Traceback (most recent call last):
   File "c:\python354-32\Lib\threading.py", line 914, in _bootstrap_inner
     self.run()
   File "c:\python354-32\Lib\threading.py", line 862, in run
     self._target(*self._args, **self._kwargs)
   File "C:\Users\JMatos\Envs\accuweather\lib\site-packages\plyer\platforms\win\
libs\balloontip.py", line 145, in balloon_tip
     WindowsBalloonTip(**kwargs)
 TypeError: __init__() got an unexpected keyword argument 'ticker'
```

If I try the same code in Android (Kivy 1.9.1) it works.

The 2nd issue is that the ticker text (which I assume would be the text that would appear next to the icon when the notification appears at the top of the Android screen) doesn't appear, Only the icon appears at the left with everything blank to the right of the icon.

If I open the notifications list, the icon, title and message appear ok.

Best regards,

JM

**Comment by KeyWeeUsr** [comment]
For Windows see #333 and try `master` even for Android, it might be already resolved.

**Comment by benjimaestro** [comment]
As of Android 5.0, there isn't a ticker any more. It was replaced with heads up notifications.

**Comment by KeyWeeUsr** [comment]
@benjimaestro if that's the case, we'll need something like

https://github.com/kivy/plyer/blob/9173cc02091b24fcb43d3586723eb68403320d71/plyer/platforms/android/notification.py#L29

to ignore the ticker if it causes troubles.

**Comment by KeyWeeUsr** [comment]
I've tested even with `setTicket()` present and there was no crash or log on the latest Oreo version.

The issue, however, was with the messed up `kwargs` in **Windows** implementation: https://github.com/kivy/plyer/blob/1a9352f85f49177a1a88c2a3326e4d2b6544a14a/plyer/platforms/win/libs/balloontip.py#L82 which was fixed in https://github.com/kivy/plyer/commit/e7731059dae37a1daf2d7310ff0ac571ae6b9dde.
