### ISSUE TITLE
ImportError: cannot import name 'brightness'

### ISSUE THREAD

**Issue by shahzadakram67** [kivy/plyer#383]
Hi i am trying to run [Plyer Brightness Example](https://github.com/kivy/plyer/blob/master/examples/brightness/main.py). But it gives
`ImportError: cannot import name 'brightness'`
All other [plyer examples ](https://github.com/kivy/plyer/tree/master/examples)are working well.

**Comment by yves-surrel** [comment]
Anything new about this issue ? 
pip install plyer installs v 1.3.0 without the brightness management, and the site-package directory content differs a lot from what appears on GitHub???

**Comment by KeyWeeUsr** [comment]
@yves-surrel Try with the new most recent release (`1.3.1`), it'll have all important stuff from `master` branch to this day.

**Comment by yves-surrel** [comment]
Yes, now there is now problem and no "import plyer" error when running on my android device. However, it seems that my Android 6.0.1 does not accept WRITE_SETTINGS permission so easily. The app crashes as soon as trying to use brightness.set_level() or brightness.current_level() in the example. No problem if I comment out the lines using those.

I found on the Web the following:

"To use WRITE_SETTINGS, based on the docs:

Have the <uses-permission> element in the manifest as normal.
Call Settings.System.canWrite() to see if you are eligible to write out settings.
If canWrite() returns false, start up the ACTION_MANAGE_WRITE_SETTINGS activity so the user can agree there to allow your app to actually write to settings."

How can this be implemented in Kivy?

**Comment by KeyWeeUsr** [comment]
@yves-surrel You can implement quite a lot of stuff via using [`pyjnius`](https://github.com/kivy/pyjnius/) and that (or Java code directly) you most likely should use for creating another activity with `ACTION_MANAGE_WRITE_SETTINGS`.

Closing issue, since the problem has been resolved.

**Comment by yves-surrel** [comment]
I answer my question 

> How can this be implemented in Kivy?

with the following code:
```
from jnius import autoclass, cast
System = autoclass('android.provider.Settings$System')
system = System()

PythonActivity = autoclass('org.kivy.android.PythonActivity')
currentActivity = cast('android.app.Activity', PythonActivity.mActivity)
context = cast('android.content.Context', currentActivity.getApplicationContext())
if not system.canWrite(context):
    settings = autoclass('android.provider.Settings')
    Intent = autoclass('android.content.Intent')
    intent = Intent()
    intent.setAction(settings.ACTION_MANAGE_WRITE_SETTINGS)
    # Open a screen on the device so that the user can allow the App to 
    # write system settings
    currentActivity.startActivity(intent)
    
# Test
from plyer import brightness
brightness_level = brightness.current_level()
brightness.set_level(100)

```
