### ISSUE TITLE
Can't pip install plyer through git

### ISSUE THREAD

**Issue by NicoLivesey** [kivy/plyer#385]
Hi, I'm facing the same kind of issue as 
- https://github.com/kivy/python-for-android/issues/833 
- https://github.com/kivy/python-for-android/issues/686
even though I thought plyer would have fix this in its last releases. So I tried to refer to the master branch of the git in the buildozer requirements as it is preconized but I am getting an invalid syntax error because of the "<<<<<<< master" in the __init__.py https://github.com/kivy/plyer/blob/master/plyer/__init__.py

I guess the problem is probably on my side but i don't have any clue...

**Comment by NicoLivesey** [comment]
Can also be related to [#257](https://github.com/kivy/plyer/issues/257)

**Comment by uluQulu** [comment]
Hi @NicoLivesey 
I used plyer in my program to send notifications to the user,
it is working very well but one of the users of my program reported this same problem while installing plyer
```
"<<<<<<< master" in the init.py 
```
I did install plyer last month and there is no problem with it, I think it happens to those who install after some changes...
Hope it gets fixed soon!

**Comment by NicoLivesey** [comment]
Hi @uluQulu 
I'm glad I am not the only one facing this. I am not aware of the last changes of pip version of plyer but the "org.renpy.android.PythonActivity" issue is 2 years old now, it is weird that it hasn't got fixed already.

**Comment by uluQulu** [comment]
![plyer error](https://user-images.githubusercontent.com/33269249/36163788-e7c1ffb2-1103-11e8-8e04-c34a4fc9ef1a.png)
this is the excat error happened
you mean this is an old issue, @NicoLivesey ?

**Comment by akshayaurora** [comment]
Sorry for the trouble, should be fixed now.

**Comment by uluQulu** [comment]
hi @akshayaurora 
thanks for the fix and thanks for writing this amazing piece, which saved me tons of lines and errors trying to write a cross-platform notification module! 
It just works flawlessly with just one line of `notification.notify()` :)
Hooray for you and all guys help plyer grow!

**Comment by NicoLivesey** [comment]
Hi @akshayaurora 
Thank you so much for your reactivity and all the work for this amazing tool. Wish you good luck.
