### ISSUE TITLE
plyer app crashes on android

### ISSUE THREAD

**Issue by apdd2003** [kivy/plyer#387]
I built apk from simple plyer example
from kivy.app import App

```
from plyer.notification import notify

class AndroidApp(App):
    def build(self):
        notify('Some title', 'Some message text')

AndroidApp().run()
```
apk crashes on   phones (tried with kitkat and marshmallow).

build command: `p4a apk --private /home/sayeem/kiviapps/ --package=org.example.pl4 --name "pl4" --version 0.1 --bootstrap=sdl2 --requirements=kivy==master,plyer,android`

logcat: attached...
[logcat1.txt](https://github.com/kivy/plyer/files/1798331/logcat1.txt)

Edit: Other simple apps from kivy examples works fine on phone

**Comment by apdd2003** [comment]
logcat contains these if it is helps. 
I am new to android app making so dont know if i am making silly mistakes.

```
Traceback (most recent call last):
I/python  (11267):    File "/home/sayeem/kiviapps/main.py", line 3, in <module>
I/python  (11267):  ImportError: No module named notification
I/python  (11267): Python for android ended.
V/SDL     (11267): onWindowFocusChanged(): false
```

**Comment by kuzeyron** [comment]
Your import is wrongly set.  
`from plyer import notification` it should be.  
[Example code](https://github.com/kivy/plyer/blob/master/examples/notification/main.py)

**Comment by apdd2003** [comment]
@kuzeyron I tried your code it is showing black screen only. No notifications.


attached. 
[logcat2.txt](https://github.com/kivy/plyer/files/1799082/logcat2.txt)

**Comment by apdd2003** [comment]
Now I changed the requirement as` --requirements kivy==master,git+https://github.com/kivy/plyer.git@master,android
` so the previous error
```
 I/python  (11267):    File "/home/sayeem/kiviapps/main.py", line 3, in <module>
I/python  (11267):  ImportError: No module named notification
```  
in logcat is not there.

But not it is showing 
```
I/python  (28255): [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
I/python  (28255):  Traceback (most recent call last):
I/python  (28255):    File "/home/sayeem/kiviapps/main.py", line 47, in <module>
I/python  (28255):    File "/home/sayeem/.local/share/python-for-android/dists/unnamed_dist_3/private/lib/python2.7/site-packages/kivy/app.py", line 800, in run
I/python  (28255):    File "/home/sayeem/kiviapps/main.py", line 41, in build
I/python  (28255):  TypeError: __init__() takes exactly 1 argument (3 given)
I/python  (28255): Python for android ended.
```
full log: 
[logcat3.txt](https://github.com/kivy/plyer/files/1799132/logcat3.txt)

**Comment by apdd2003** [comment]
nice! at least got success with other example [vibrator](https://github.com/kivy/plyer/tree/master/examples/vibrator).
app worked fine on mobile. 
command: 
`p4a apk --private /home/sayeem/kiviapps/ --package=org.example.pl12 --name "pl12" --version 0.1 --bootstrap=sdl2 --requirements kivy==master,git+https://github.com/kivy/plyer.git@master --permission VIBRATE`

but still would like to solve the notification example.

**Comment by apdd2003** [comment]
again tried plyer notification example without android as requirements.
`p4a apk --private /home/sayeem/kiviapps/ --package=org.example.pl13 --name "pl13" --version 0.1 --bootstrap=sdl2 --requirements kivy==master,git+https://github.com/kivy/plyer.git@master
`

now logcat does not show any error as above and it seems from logcat that app running and exiting normally. but still nothing is shown on notification bar...
logcat:

[logcat.txt](https://github.com/kivy/plyer/files/1799155/logcat.txt)

**Comment by apdd2003** [comment]
as I mentioned in earlier post I might be making a silly mistake. That is right. I did not include .kv file in folder, I just ran built main.py... now app is running fine. simple notification is showing in panel. but fancy notification is not showing. may be because I have to include those image file in p4a arguments??

**Comment by kuzeyron** [comment]
Could you upload your project to GitHub and link it to here so we can have a look at it?
