### ISSUE TITLE
storagepath.py  _get_application_dir: NotImplementedError

### ISSUE THREAD

**Issue by smpsupply** [kivy/plyer#389]
Hi, I am compiling Android app with buildozer, kivy and plyer under osx. The main.py is came from plyer storagepath example. Below is from logcat. I can't figure out what is the problem here. Could someone please advise how plyer facedes can be then redirect to platform/android/storagepath.py?

I tried to install the same library from git/plyer under osx and tried to execute "from plyer import email" in python. Print out the file path is point to macosx/email.py. Seem like the plyer has no issue under osx.

But for buildozer, this redirection seem not work automatically. Hope experts can help. Thanks! 

I/python  (26662):    File "kivy/_event.pyx", line 1225, in kivy._event.EventObservers.dispatch (kivy/_event.c:14035)
I/python  (26662):    File "kivy/_event.pyx", line 1109, in kivy._event.EventObservers._dispatch (kivy/_event.c:12816)
I/python  (26662):    File "/Users/smpsupply/storagepath/.buildozer/android/platform/build/dists/StoragePath/private/lib/python2.7/site-packages/kivy/lang/builder.py", line 64, in custom_callback
I/python  (26662):    File "<string>", line 37, in <module>
I/python  (26662):    File "/Users/smpsupply/storagepath/.buildozer/android/platform/build/dists/StoragePath/private/lib/python2.7/site-packages/plyer/facades/storagepath.py", line 95, in get_application_dir
I/python  (26662):    File "/Users/smpsupply/storagepath/.buildozer/android/platform/build/dists/StoragePath/private/lib/python2.7/site-packages/plyer/facades/storagepath.py", line 124, in _get_application_dir
I/python  (26662):  NotImplementedError

**Comment by smpsupply** [comment]
I just read the plyer code and found Proxy and  under _ensure_obj add "wrong_location" label.
After i checked again on the logcat, found there is no module name android.
Look like there is no android module and causing NotImplementedError. 
I would need to checked how to install android module.
Thanks all!

I/python  ( 2816):  Traceback (most recent call last):
I/python  ( 2816):    File "/Users/smpsupply/storagepath/.buildozer/android/platform/build/dists/StoragePath/private/lib/python2.7/site-packages/plyer/utils.py", line 88, in _ensure_obj
I/python  ( 2816):    File "/Users/smpsupply/storagepath/.buildozer/android/platform/build/dists/StoragePath/private/lib/python2.7/site-packages/plyer/platforms/android/storagepath.py", line 8, in <module>
I/python  ( 2816):  ImportError: No module named android
I/python  ( 2816): wrong_location
I/python  ( 2816): <plyer.facades.storagepath.StoragePath object at 0x69048530>
I/python  ( 2816): [INFO   ] [Base        ] Leaving application in progress...

**Comment by kuzeyron** [comment]
Just for fun. Try adding android to the requirements.

**Comment by smpsupply** [comment]
Thanks kuzeyron. As you said, the android module cannot be found can be solved by just modifying the buildozer.spec, under 
requirements = kivy, hostpython2, https://codeload.github.com/kivy/plyer/zip/master, android

Initially, i tried to import in python under osx environment but i found that module not found. Actually android module will just copy to apk if this apk is compiled by python-for-android. So i think under normal os it cannot detected unless it is run on android system. Hope my experience help others. Thanks!

**Comment by kuzeyron** [comment]
You should really update everything you have to the latest. Kivy, Plyer & Buildozer.
The problem why it isn't auto getting the android could be if some packages are old.

We could see if @inclement have any ideas!

**Comment by smpsupply** [comment]
Thank you. That is actually weird for me. For Buildozer.spec, requirements option, sometimes I need to force it kivy==1.10.0 to get the latest version. For plyer, if i simply enter plyer, it is not get the latest version, storagepath.py just missing in the path. That is i just put the full link from git: https://codeload.github.com/kivy/plyer/zip/master. Seem like the default download path not up-to-date yet. I will check the buildozer log file and to see the actual download path and report the discrepency.

**Comment by kuzeyron** [comment]
Try updating everything on your Mac/PC. It should solve your problems!

**Comment by smpsupply** [comment]
ok Thanks!
