### ISSUE TITLE
Python 3 TabError

### ISSUE THREAD

**Issue by slinkymanbyday** [kivy/plyer#398]
When doing a pip install from git, it gives a TabError. Looks like spaces and tabs are being mixed.

`File "/private/var/folders/dx/_1pwf3z10t31sn_hk_cv6xmc0000gn/T/pip-g7_11zw6-build/plyer/facades/processors.py", line 39
        raise NotImplementedError()
                                  ^
    TabError: inconsistent use of tabs and spaces in indentation
`

**Comment by tshirtman** [comment]
fixed by a9f05220791f9cf50a45be43c615c0fa76249e1a

thanks for reporting!
