### ISSUE TITLE
GPS example crashes

### ISSUE THREAD

**Issue by lipi** [kivy/plyer#40]
Trying to run the following code (from the docs):

```
from time import sleep
from plyer import gps

def print_locations(**kwargs):
    print 'lat: {lat}, lon: {lon}'.format(**kwargs)

gps.configure(on_location=print_locations)
gps.start()
sleep(5)
gps.stop()
```

However it crashes:

```
I/python  (29941): Initialize Python for Android
I/python  (29941): ['/data/data/org.test.gps/files/lib/python2.7/site-packages', '/data/data/org.test.gps/files/lib/site-python']
I/python  (29941): Android path ['/data/data/org.test.gps/files/lib/python27.zip', '/data/data/org.test.gps/files/lib/python2.7', '/data/data/org.test.gps/files/lib/python2.7/lib-dynload', '/data/data/org.test.gps/files/lib/python2.7/site-packages', '/data/data/org.test.gps/files']
I/python  (29941): Android kivy bootstrap done. __name__ is __main__
I/python  (29941): Run user program, change dir and execute main.py
I/python  (29941): Traceback (most recent call last):
I/python  (29941):   File "/home/lipi/git/repka2/android/main.py", line 7, in <module>
I/python  (29941):   File "/home/lipi/git/p4a/build/python-install/lib/python2.7/site-packages/plyer/facades.py", line 189, in configure
I/python  (29941):   File "/home/lipi/git/p4a/build/python-install/lib/python2.7/site-packages/plyer/platforms/android/gps.py", line 72, in _configure
I/python  (29941):   File "/home/lipi/git/p4a/build/python-install/lib/python2.7/site-packages/plyer/platforms/android/gps.py", line 20, in __init__
I/python  (29941):   File "jnius_proxy.pxi", line 31, in jnius.jnius.PythonJavaClass.__init__ (jnius/jnius.c:21301)
I/python  (29941):   File "jnius_proxy.pxi", line 182, in jnius.jnius.create_proxy_instance (jnius/jnius.c:23496)
I/python  (29941):   File "jnius_export_class.pxi", line 556, in jnius.jnius.JavaMethod.__call__ (jnius/jnius.c:17318)
I/python  (29941):   File "jnius_conversion.pxi", line 57, in jnius.jnius.populate_args (jnius/jnius.c:5405)
I/python  (29941):   File "jnius_utils.pxi", line 74, in jnius.jnius.check_assignable_from (jnius/jnius.c:3449)
I/python  (29941): jnius.jnius.JavaException: Invalid instance of 'org/jnius/NativeInvocationHandler' passed for a 'java/lang/reflect/InvocationHandler'
I/python  (29941): Python for android ended.
```

**Comment by iamryanmoreno** [comment]
I am having trouble running the gps example in plyer.. I runned it but it is stuck with getting Click start to get GPS location updates. I runned it in kivy luncher with plyer and buildozer inside. can u please provide a screeshot of what should be seen after running the application and provide a clear step by step of running properly this program. PLease..............

**Comment by brousch** [comment]
I don't think Kivy Launcher has the Android permissions necessary to use
the GPS. You should compile an APK using buildozer and install it to your
device. Putting buildozer in your project does nothing.

On Fri, Feb 13, 2015 at 4:16 AM, iamryanmoreno <notifications@github.com>
wrote:

> I am having trouble running the gps example in plyer.. I runned it but it
> is stuck with getting Click start to get GPS location updates. I runned it
> in kivy luncher with plyer and buildozer inside. can u please provide a
> screeshot of what should be seen after running the application and provide
> a clear step by step of running properly this program. PLease..............
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kivy/plyer/issues/40#issuecomment-74225229>.
>



-- 
 Ben Rousch
   brousch@gmail.com
   http://clusterbleep.net/

**Comment by iamryanmoreno** [comment]
can i get an apk of the plyer example for gps? i will install it in my phone because I am really curious about this python program?

**Comment by iamryanmoreno** [comment]
why is that when i runned the other examples, its working in my kivy launcher only that of gps is not. can someone provide another library for accessing gps in kivy?

**Comment by jeyfrinjulian** [comment]
hello, glad , download the GPS example plyer https://github.com/kivy/plyer/tree/master/examples/gps but for android in buildozer compile the application does not start when installed on my device with android 4.4.4 Error throws me NotImplementedError. thanks
