### ISSUE TITLE
notification not working on android

### ISSUE THREAD

**Issue by J0K3RAS** [kivy/plyer#402]
Lately I've been using the `notification.notify(message='test message')` on linux with great success
The probem comes when I try it on andoid  (using pydroid3 or compiling an apk with kivy), where it gives error: `NotImplementedError`.

Please note that `vibrator.vibrate(10)` works fine, and the piece of code tested is the same as the one working on linux.

I can provide you the adb logs from my .apk or the output log from pydroid3 console, in case you cannot reproduce the problem.

The plyer version used on android, is the one that is available on pypi

**Comment by akshayaurora** [comment]
python-for-android version?
which toolchain ? sdl2? old_toolchain? py3 crystax?

**Comment by J0K3RAS** [comment]
I don't use python3 crystax

I use the kivy vm with buildozer

Toolchain, sdl2, old_toolchain, are the default versions that come with kivy vm

**Comment by morgansong** [comment]
I had same issue. Don't know the reason why main.py works fine with correct notification in win10 laptop but don't work on my android phone after I packed to APK successfully throught the buildozer VM with default setting.

**Comment by KeyWeeUsr** [comment]
Notifications work properly. Make sure you have `android` in your requirements.
