### ISSUE TITLE
Email Support for Android < 4.0

### ISSUE THREAD

**Issue by trivedigaurav** [kivy/plyer#42]
Add email support (open mail client) for android < 4.0.

**Comment by thegrymek** [comment]
Hi,

How to test it?
I tested on Samung Galaxy, ver 2.3 and it works.

I wrote recipient, subject and text. 
Then Clicked 'Send Email' and opened gmail with new email with data from kivy.

best regards

**Comment by thegrymek** [comment]
https://github.com/kivy/plyer/pull/140
