### ISSUE TITLE
macOS storagepath uses non-standard path for get_home_dir()

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/plyer#450]
All other methods return via macOS Obj-C API paths in a `file://` URI scheme except `get_home_dir()` which returns an ordinary unix/linux path `/Users/...`.

**Comment by Nephyx** [comment]
Fixed this, will create pull request.

**Comment by KeyWeeUsr** [comment]
closed by #475, ref #482

**Comment by StudioPetrikas** [comment]
Using Plyer 2.1.0 on macOS 13.4.1

Trying to export an image to ~/Pictures/AppName/File.jpg; but instead it creates "file/" folder. 
So the full path becomes ~/file//Users/Username//Pictures/AppName/File.jpg.

This is the output from Python: file saved to: file:///Users/Username//Pictures/AppName/File.jpg

code that calls: `app_save_path = os.path.join(storagepath.get_pictures_dir(), 'AppName')`

Is this related? This command works well on Windows and Android, but trips on macOS
