### ISSUE TITLE
GNU/Linux wifi disconnect() not working on Ubuntu 15.04+

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/plyer#452]
ref: [this comment](https://askubuntu.com/questions/434660/how-can-i-disable-my-internet-connection-from-terminal#comment961012_434664) from [question](https://askubuntu.com/a/434664/845306) as AskUbuntu about this line:

https://github.com/kivy/plyer/blob/ee44e6e786f99ba5d620fb66ce558c1bc50ffc54/plyer/platforms/linux/wifi.py#L91

> Regarding @Radu's original response, it no longer works in Ubuntu 15.04. Instead nmcli networking off is the new way to shut down all networking until manually restarted, and it does not require sudo.

Probably a more general approach would require `wpa_supplicant` and other lower-level binaries instead of [NetworkManager / `nmcli`](https://github.com/NetworkManager/NetworkManager) and it'd certainly make testing easier.

**Comment by xhimanshuz** [comment]
#470 work's for it

**Comment by KeyWeeUsr** [comment]
Fixed by #473.
