### ISSUE TITLE
plyer notifications raising NotImplementedError on android

### ISSUE THREAD

**Issue by tripluS-h** [kivy/plyer#467]
Using the example code (and any other instance of notification.notify) crashes on my android device.
Also worth noting is that it works flawlessly on my (linux) laptop.
Logcat:

11-06 11:56:36.878 16302 16321 I python  :  Traceback (most recent call last):
11-06 11:56:36.879 16302 16321 I python  :    File "/home/liam/Documents/AndroidServiceTest/notification_test/plyer/examples/notification/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/plyer/utils.py", line 95, in _ensure_obj
11-06 11:56:36.879 16302 16321 I python  :    File "/home/liam/Documents/AndroidServiceTest/notification_test/plyer/examples/notification/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/plyer/platforms/android/notification.py", line 5, in <module>
11-06 11:56:36.880 16302 16321 I python  :  ImportError: No module named config
11-06 11:56:36.880 16302 16321 I python  : [INFO   ] [Base        ] Leaving application in progress...
11-06 11:56:36.881 16302 16321 I python  :  Traceback (most recent call last):
11-06 11:56:36.881 16302 16321 I python  :    File "/home/liam/Documents/AndroidServiceTest/notification/.buildozer/android/app/main.py", line 35, in <module>
11-06 11:56:36.882 16302 16321 I python  :    File "/home/liam/Documents/AndroidServiceTest/notification_test/plyer/examples/notification/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/app.py", line 826, in run
11-06 11:56:36.882 16302 16321 I python  :    File "/home/liam/Documents/AndroidServiceTest/notification_test/plyer/examples/notification/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/base.py", line 502, in runTouchApp
11-06 11:56:36.883 16302 16321 I python  :    File "/home/liam/Documents/AndroidServiceTest/notification_test/plyer/examples/notification/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 403, in mainloop
11-06 11:56:36.884 16302 16321 I python  :    File "/home/liam/Documents/AndroidServiceTest/notification_test/plyer/examples/notification/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 289, in _mainloop
11-06 11:56:36.884 16302 16321 I python  :    File "/home/liam/Documents/AndroidServiceTest/notification_test/plyer/examples/notification/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/base.py", line 340, in idle
11-06 11:56:36.885 16302 16321 I python  :    File "/home/liam/Documents/AndroidServiceTest/notification_test/plyer/examples/notification/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/base.py", line 325, in dispatch_input
11-06 11:56:36.885 16302 16321 I python  :    File "/home/liam/Documents/AndroidServiceTest/notification_test/plyer/examples/notification/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/base.py", line 231, in post_dispatch_input
11-06 11:56:36.885 16302 16321 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7727)
11-06 11:56:36.886 16302 16321 I python  :    File "/home/liam/Documents/AndroidServiceTest/notification_test/plyer/examples/notification/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 1360, in on_motion
11-06 11:56:36.887 16302 16321 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7727)
11-06 11:56:36.887 16302 16321 I python  :    File "/home/liam/Documents/AndroidServiceTest/notification_test/plyer/examples/notification/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 1376, in on_touch_down
11-06 11:56:36.887 16302 16321 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7727)
11-06 11:56:36.888 16302 16321 I python  :    File "/home/liam/Documents/AndroidServiceTest/notification_test/plyer/examples/notification/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/uix/widget.py", line 460, in on_touch_down
11-06 11:56:36.888 16302 16321 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7727)
11-06 11:56:36.889 16302 16321 I python  :    File "/home/liam/Documents/AndroidServiceTest/notification_test/plyer/examples/notification/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/uix/behaviors/button.py", line 151, in on_touch_down
11-06 11:56:36.890 16302 16321 I python  :    File "kivy/_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7682)
11-06 11:56:36.890 16302 16321 I python  :    File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch (kivy/_event.c:13525)
11-06 11:56:36.891 16302 16321 I python  :    File "kivy/_event.pyx", line 1098, in kivy._event.EventObservers._dispatch (kivy/_event.c:12357)
11-06 11:56:36.891 16302 16321 I python  :    File "/home/liam/Documents/AndroidServiceTest/notification_test/plyer/examples/notification/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/lang/builder.py", line 64, in custom_callback
11-06 11:56:36.892 16302 16321 I python  :    File "/data/data/org.test.notiexample/files/notificationdemo.kv", line 22, in <module>
11-06 11:56:36.892 16302 16321 I python  :      on_press: root.do_notify(mode='normal')
11-06 11:56:36.893 16302 16321 I python  :    File "/home/liam/Documents/AndroidServiceTest/notification/.buildozer/android/app/main.py", line 23, in do_notify
11-06 11:56:36.893 16302 16321 I python  :    File "/home/liam/Documents/AndroidServiceTest/notification_test/plyer/examples/notification/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/plyer/facades/notification.py", line 57, in notify
11-06 11:56:36.894 16302 16321 I python  :    File "/home/liam/Documents/AndroidServiceTest/notification_test/plyer/examples/notification/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/plyer/facades/notification.py", line 62, in _notify
11-06 11:56:36.894 16302 16321 I python  :  NotImplementedError: No usable implementation found!
11-06 11:56:36.925 16302 16321 I python  : Python for android ended.

haven't found any information about this around, any suggestions? Or other ways to send android notifications?

**Comment by KeyWeeUsr** [comment]
This is due to this line:

https://github.com/kivy/plyer/blob/2f6e2a98e2f2d12ddf5c2dade5baec363ea20989/plyer/platforms/android/notification.py#L5

which tries to import the `android.config` part i.e. this:

https://github.com/kivy/python-for-android/blob/b64b9eccd2753f4233fe21bc28d8eb96ef951557/pythonforandroid/recipes/android/src/android/_android.pyx#L3

and it seems to me from this error that you do not have a compiled `android` module. Also, you use `pygame` which is an old bootstrap instead of the new one (`sdl2`). Try to add `android` to your requirements.

Basically what happened is that you don't have `android` module from p4a as expected from the notification implementation for android platform and the first import wants the value from:

https://github.com/kivy/python-for-android/blob/b64b9eccd2753f4233fe21bc28d8eb96ef951557/pythonforandroid/recipes/android/__init__.py#L54

so that it can use it in `pyjnius`.

Note: whether it works on linux or not means only that the *example Kivy application* works, not that the notification itself works. Those are various different files located in `platforms/<platform>/notification.py` files.

**Comment by tripluS-h** [comment]
How can I do that through buildozer? Compiling using the android_new target also leads to a crash with the same

**Comment by tripluS-h** [comment]
Holy shit, just realized my buildozer is waaay out of date, closing this until I get that sorted out
