### ISSUE TITLE
jnius.jnius.JavaException: Class not found 'android/content/INTENT'

### ISSUE THREAD

**Issue by yjmlzy** [kivy/plyer#479]
I am having trouble running the battery example in plyer on Android.  
how to fix this error?

I/python  ( 1517): [INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system

I/python  ( 1517): [INFO   ] [GL          ] Backend used <gl>

I/python  ( 1517): [INFO   ] [GL          ] OpenGL version <OpenGL ES 3.0>

I/python  ( 1517): [INFO   ] [GL          ] OpenGL vendor <Qualcomm>

I/python  ( 1517): [INFO   ] [GL          ] OpenGL renderer <Adreno (TM) 540>

I/python  ( 1517): [INFO   ] [GL          ] OpenGL parsed version: 3, 0

I/python  ( 1517): [INFO   ] [GL          ] Texture max size <16384>

I/python  ( 1517): [INFO   ] [GL          ] Texture max units <16>

I/python  ( 1517): [INFO   ] [Window      ] auto add sdl2 input provider

I/python  ( 1517): [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked

I/python  ( 1517): [WARNING] [Base        ] Unknown <android> provider

I/python  ( 1517): [INFO   ] [Base        ] Start application main loop

I/python  ( 1517): [INFO   ] [GL          ] NPOT texture support is available

I/art     (  412): Explicit concurrent mark sweep GC freed 15106(1200KB) AllocSpace objects, 42(672KB) LOS objects, 33% free, 8MB/13MB, paused 305us total 23.251ms

I/python  ( 1517): [INFO   ] [Base        ] Leaving application in progress...

I/python  ( 1517):  Traceback (most recent call last):

I/python  ( 1517):    File "/home/kivy/myproj/.buildozer/android/app/main.py", line 56, in <module>

I/python  ( 1517):    File "/home/kivy/myproj/.buildozer/android/platform/build/dists/myapp/private/lib/python2.7/site-packages/kivy/app.py", line 828, in run

I/python  ( 1517):    File "/home/kivy/myproj/.buildozer/android/platform/build/dists/myapp/private/lib/python2.7/site-packages/kivy/base.py", line 504, in runTouchApp

I/python  ( 1517):    File "/home/kivy/myproj/.buildozer/android/platform/build/dists/myapp/private/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 663, in mainloop

I/python  ( 1517):    File "/home/kivy/myproj/.buildozer/android/platform/build/dists/myapp/private/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 405, in _mainloop

I/python  ( 1517):    File "/home/kivy/myproj/.buildozer/android/platform/build/dists/myapp/private/lib/python2.7/site-packages/kivy/base.py", line 342, in idle

I/python  ( 1517):    File "/home/kivy/myproj/.buildozer/android/platform/build/dists/myapp/private/lib/python2.7/site-packages/kivy/base.py", line 327, in dispatch_input

I/python  ( 1517):    File "/home/kivy/myproj/.buildozer/android/platform/build/dists/myapp/private/lib/python2.7/site-packages/kivy/base.py", line 233, in post_dispatch_input

I/python  ( 1517):    File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:8191)

I/python  ( 1517):    File "/home/kivy/myproj/.buildozer/android/platform/build/dists/myapp/private/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 1188, in on_motion

I/python  ( 1517):    File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:8191)

I/python  ( 1517):    File "/home/kivy/myproj/.buildozer/android/platform/build/dists/myapp/private/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 1204, in on_touch_down

I/python  ( 1517):    File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:8191)

I/python  ( 1517):    File "/home/kivy/myproj/.buildozer/android/platform/build/dists/myapp/private/lib/python2.7/site-packages/kivy/uix/widget.py", line 457, in on_touch_down

I/python  ( 1517):    File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:8191)

I/python  ( 1517):    File "/home/kivy/myproj/.buildozer/android/platform/build/dists/myapp/private/lib/python2.7/site-packages/kivy/uix/widget.py", line 457, in on_touch_down

I/python  ( 1517):    File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:8191)

I/python  ( 1517):    File "/home/kivy/myproj/.buildozer/android/platform/build/dists/myapp/private/lib/python2.7/site-packages/kivy/uix/behaviors/button.py", line 151, in on_touch_down

I/python  ( 1517):    File "kivy/_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:8146)

I/python  ( 1517):    File "kivy/_event.pyx", line 1225, in kivy._event.EventObservers.dispatch (kivy/_event.c:14035)

I/python  ( 1517):    File "kivy/_event.pyx", line 1109, in kivy._event.EventObservers._dispatch (kivy/_event.c:12816)

I/python  ( 1517):    File "/home/kivy/myproj/.buildozer/android/platform/build/dists/myapp/private/lib/python2.7/site-packages/kivy/lang/builder.py", line 64, in custom_callback

I/python  ( 1517):    File "<string>", line 11, in <module>

I/python  ( 1517):    File "/home/kivy/myproj/.buildozer/android/app/main.py", line 41, in get_status

I/python  ( 1517):    File "/home/kivy/myproj/.buildozer/android/platform/build/dists/myapp/private/lib/python2.7/site-packages/plyer/utils.py", line 116, in __getattribute__

I/python  ( 1517):    File "/home/kivy/myproj/.buildozer/android/platform/build/dists/myapp/private/lib/python2.7/site-packages/plyer/facades/battery.py", line 42, in status

I/python  ( 1517):    File "/home/kivy/myproj/.buildozer/android/platform/build/dists/myapp/private/lib/python2.7/site-packages/plyer/facades/battery.py", line 49, in get_state

I/python  ( 1517):    File "/home/kivy/myproj/.buildozer/android/platform/build/dists/myapp/private/lib/python2.7/site-packages/plyer/platforms/android/battery.py", line 26, in _get_state

I/python  ( 1517):    File "jnius/jnius_export_func.pxi", line 9, in jnius.jnius.cast (jnius/jnius.c:16763)

I/python  ( 1517):    File "/home/kivy/myproj/.buildozer/android/platform/build/dists/myapp/private/lib/python2.7/site-packages/jnius/reflect.py", line 159, in autoclass

I/python  ( 1517):    File "jnius/jnius_export_func.pxi", line 26, in jnius.jnius.find_javaclass (jnius/jnius.c:17118)

I/python  ( 1517):  jnius.jnius.JavaException: Class not found 'android/content/INTENT'

**Comment by KeyWeeUsr** [comment]
This has been fixed by https://github.com/kivy/plyer/commit/fa1f325e33094207a83b496b4f451f4675049b34 and I also made a new release a while ago (`1.3.2`). Update your `plyer` package. :)
