### ISSUE TITLE
Vibrate revision in api 26

### ISSUE THREAD

**Issue by Archaeus6** [kivy/plyer#501]
Dev requested to have this issue submitted. Vibrate was revised in API 26 which causes a crash on Android using 27. 

Code:

#from plyer import vibrator

#vibrator.vibrate(2)

Log:

"
04-04 21:31:22.899  1996  2038 I python  : [INFO   ] [Base        ] Leaving application in progress...
04-04 21:31:22.899  1996  2038 I python  :  Traceback (most recent call last):
04-04 21:31:22.900  1996  2038 I python  :    File "/home/archaeus/my_files/python_files/DragonWars/.buildozer/android/app/main.py", line 701, in <module>
04-04 21:31:22.900  1996  2038 I python  :    File "/home/archaeus/my_files/python_files/DragonWars/.buildozer/android/platform/build/build/python-installs/dragon1/kivy/app.py", line 855, in run
04-04 21:31:22.901  1996  2038 I python  :    File "/home/archaeus/my_files/python_files/DragonWars/.buildozer/android/platform/build/build/python-installs/dragon1/kivy/base.py", line 502, in runTouchApp
04-04 21:31:22.902  1996  2038 I python  :    File "/home/archaeus/my_files/python_files/DragonWars/.buildozer/android/platform/build/build/python-installs/dragon1/kivy/core/window/window_sdl2.py", line 730, in mainloop
04-04 21:31:22.903  1996  2038 I python  :    File "/home/archaeus/my_files/python_files/DragonWars/.buildozer/android/platform/build/build/python-installs/dragon1/kivy/core/window/window_sdl2.py", line 465, in _mainloop
04-04 21:31:22.903  1996  2038 I python  :    File "/home/archaeus/my_files/python_files/DragonWars/.buildozer/android/platform/build/build/python-installs/dragon1/kivy/base.py", line 337, in idle
04-04 21:31:22.904  1996  2038 I python  :    File "/home/archaeus/my_files/python_files/DragonWars/.buildozer/android/platform/build/build/python-installs/dragon1/kivy/clock.py", line 581, in tick
04-04 21:31:22.905  1996  2038 I python  :    File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
04-04 21:31:22.905  1996  2038 I python  :    File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
04-04 21:31:22.906  1996  2038 I python  :    File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
04-04 21:31:22.907  1996  2038 I python  :    File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
04-04 21:31:22.908  1996  2038 I python  :    File "/home/archaeus/my_files/python_files/DragonWars/.buildozer/android/app/main.py", line 551, in enemy_attack_countdown
04-04 21:31:22.908  1996  2038 I python  :    File "/home/archaeus/my_files/python_files/DragonWars/.buildozer/android/app/main.py", line 567, in enemy_attack
04-04 21:31:22.909  1996  2038 I python  :    File "/home/archaeus/my_files/python_files/DragonWars/.buildozer/android/platform/build/build/python-installs/dragon1/plyer/facades/vibrator.py", line 52, in vibrate
04-04 21:31:22.910  1996  2038 I python  :    File "/home/archaeus/my_files/python_files/DragonWars/.buildozer/android/platform/build/build/python-installs/dragon1/plyer/platforms/android/vibrator.py", line 24, in _vibrate
04-04 21:31:22.910  1996  2038 I python  :    File "jnius/jnius_export_class.pxi", line 742, in jnius.jnius.JavaMethod.__call__
04-04 21:31:22.911  1996  2038 I python  :  jnius.jnius.JavaException: Invalid call, number of argument mismatch, got 1 need 4
04-04 21:31:22.911  1996  2038 I python  : Python for android ended.
04-04 21:31:23.181   978  4986 V AudioFlinger: 1996 died, releasing its sessions
04-04 21:31:23.181   978  4986 V AudioFlinger:  pid 2511 @ 0
04-04 21:31:23.181   978  4986 V AudioFlinger:  pid 2202 @ 1
04-04 21:31:23.181   978  4986 V AudioFlinger:  pid 1996 @ 2
04-04 21:31:23.181   978  4986 V AudioFlinger:  removing entry for pid 1996 session 2841
04-04 21:31:23.182   686  1791 E SurfaceFlinger: Failed to find layer (SurfaceView - org.test.dragon1/org.kivy.android.PythonActivity#0) in layer parent (no-parent).
04-04 21:31:23.182   686  1791 E SurfaceFlinger: Failed to find layer (Background for - SurfaceView - org.test.dragon1/org.kivy.android.PythonActivity#0) in layer parent (no-parent).
04-04 21:31:23.182  1842  2090 W InputDispatcher: channel '47ed371 org.test.dragon1/org.kivy.android.PythonActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
04-04 21:31:23.182  1842  2090 E InputDispatcher: channel '47ed371 org.test.dragon1/org.kivy.android.PythonActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
04-04 21:31:23.183  1842  5078 I ActivityManager: Process org.test.dragon1 (pid 1996) has died: fore TOP 
04-04 21:31:23.184  1842  5078 W ActivityManager: Force removing ActivityRecord{6ece801 u0 org.test.dragon1/org.kivy.android.PythonActivity t12478}: app died, no saved state
04-04 21:31:23.186   647   647 D sensors_hal_SMGR: enable:sensor(android.sensor.accelerometer) Deactivating sensor handle=1
04-04 21:31:23.186   647   647 D sensors_hal_Util: waitForResponse: timeout=5000
04-04 21:31:23.187   647   647 D sensors_hal_SMGR: SMGRReportDelete: Rcvd success response from request
04-04 21:31:23.186  1842  1938 W zygote  : kill(-1996, 9) failed: No such process
04-04 21:31:23.198  1842  5078 D InputDispatcher: Focus left window: Window{47ed371 u0 org.test.dragon1/org.kivy.android.PythonActivity}
04-04 21:31:23.203  1842  5078 I WindowManager: Failed to capture screenshot of Token{35546a6 ActivityRecord{6ece801 u0 org.test.dragon1/org.kivy.android.PythonActivity t12478 f}} appWin=Window{47ed371 u0 org.test.dragon1/org.kivy.android.PythonActivity} drawState=4
04-04 21:31:23.204  1842  5078 W InputDispatcher: Attempted to unregister already unregistered input channel '47ed371 org.test.dragon1/org.kivy.android.PythonActivity (server)'
04-04 21:31:23.209  1842  5078 D InputDispatcher: Window went away: Window{47ed371 u0 org.test.dragon1/org.kivy.android.PythonActivity}
04-04 21:31:23.212   978  1518 V audio_hw_primary: out_get_latency: Latency 80
04-04 21:31:23.214  1842  6343 W WindowManager: Failed looking up window callers=com.android.server.wm.WindowManagerService.windowForClientLocked:7767 com.android.server.wm.WindowState$DeathRecipient.binderDied:2556 android.os.BinderProxy.sendDeathNotice:862 
04-04 21:31:23.214  1842  6343 I WindowManager: WIN DEATH: null
04-04 21:31:23.230  1842  2159 D WifiWatchdogStateMachine: EVENT_CHECK_IMS_CALL_STATE received
04-04 21:31:23.230  1842  2159 D WifiWatchdogStateMachine: OnlineWatchState handleRssiChange() imscallstate : 0
04-04 21:31:23.230  1842  1938 W zygote  : kill(-1996, 9) failed: No such process
04-04 21:31:23.232   978  1518 V audio_hw_primary: out_get_latency: Latency 80
04-04 21:31:23.252   978  1518 V audio_hw_primary: out_get_latency: Latency 80
04-04 21:31:23.252   644   644 W PHHandler: [PH] hint id(61440) is not supported
04-04 21:31:23.252   970  1019 I PowerRM : System FW:1 IC:0 SO:0 GT:1 CAPP:-1 APP:0
"

**Comment by ogaskell** [comment]
This issue doesn't seem to be fixed. I'm using the latest version of the whole Kivy suite from master.

**Comment by Zen-CODE** [comment]
@ogaskell  You'd need to be a bit more specific in order for this comment to be useful. i.e. which exact kivy version? Which exact version of plyer? And when you say it's not fixed, what happens? Nothing or a crash? And logs? Thanks
