### ISSUE TITLE
timeout parameter in notifications doesn't work in windows 10

### ISSUE THREAD

**Issue by fjleon1980** [kivy/plyer#503]
no matter what timeout=X value i put it, the notification's time on the screen is always the same, as long as it's above 5 seconds

putting a timeout=20 for example, shows the notification for about 5-6 seconds but the python interpreter is still "stuck" because it's waiting for 20 seconds to continue with the script.

if using a lower than 5 seconds as a value, it actually exists before the regular 5-6 seconds are up.

i would like to use timeout=0 and make the notification stay on screen until i closed it manually

**Comment by starboy-jb** [comment]
I also facing the same problem.

**Comment by deepghodasara1999** [comment]
You have to change notification time for windows from ..

start > settings > ease to access > display > Show notification for

Default time for this in windows 10 is 5 sec, so for whatever value of timeout your notification will be display only for 5 sec.

**Comment by darkcurrent** [comment]
> You have to change notification time for windows from ..
> 
> start > settings > ease to access > display > Show notification for
> 
> Default time for this in windows 10 is 5 sec, so for whatever value of timeout your notification will be display only for 5 sec.

It is a controllable parameter. With win10toast duration can be controlled but with plyer I had no luck either. So Windows10 allows it. The user is not has to change the duration from the windows settings.

**Comment by someone20dz** [comment]
@darkcurrent 
Windows 10 by default has a 5 seconds timeout the only way we can change it is through the windows settings:
1. Go to settings
2. Ease to access
3. Scroll down to where it says Show notification for

![Screenshot_28](https://user-images.githubusercontent.com/58312417/154495987-d3c05b34-161d-427d-8543-eaa5d6ff4516.png)

However, does the timeout works for Linux and Mac OS?

Another solution is to use another module, unfortunately.

If anyone else has a solution please Let me know.

**Comment by Julian-O** [comment]
Closing as it appears to not be possible to solve.

However, if you have more information, please let us know.
