### ISSUE TITLE
notification.notify crashes Android Pie devices

### ISSUE THREAD

**Issue by azvampyre** [kivy/plyer#504]
I have used the notification.notify and tested on a dozen phones. All work perfectly except the Android 9.0 phones which crash when requesting the notify method.

I searched to see if there was a new Permission for this but found nothing.

The only line in the error log states "calling JNI before it's ready" but it's only info, not a warning nor error.

Note that the toast method works, its the actionbar notification that has problems.

**Comment by azvampyre** [comment]
I ran it through Android Studio and got more information.
This is the error that was produced according to Logcat

attempt to pass an instance of java.lang.Class<android.app.NotificationManager> as argument 1 to java.lang.Object android.app.Activity.getSystemService(java.lang.String)

java_vm_ext.cc:561] JNI DETECTED ERROR IN APPLICATION: bad arguments passed to java.lang.Object android.app.Activity.getSystemService(java.lang.String) (see above for details)

**Comment by seanwlk** [comment]
Notifications don't work indeed, only toast notifications work for me on Android Pie.

**Comment by azvampyre** [comment]
It was quicker for me to rewrite the entire app in Java than continue using Python and multiple third party plugins that rarely work anyways. I really hated Python and glad to be rid of it.

**Comment by javiuribe** [comment]
The easiest way is to pass a toast=True in the kwargs to the notify method to use the toast notifications as the regular notifications fail in newer android versions

**Comment by SidnetyAtheos** [comment]
I have the same problem does anyone know a solution

**Comment by pakal** [comment]
I've just started dev on kivy/android, so I'm not at ease, but it seems that the probleme is here below: the android notifications.py code should call _get_notification_service(), and not pass a manager instance to activity.getSystemService().



``` FILE  plyer/platforms/android/notification.py

    def _get_notification_service(self):
        if not self._ns:
            self._ns = activity.getSystemService(
                Context.NOTIFICATION_SERVICE
            )
        return self._ns

    def _build_notification_channel(self, name):
        '''
        Create a NotificationChannel using channel id of the application
        package name (com.xyz, org.xyz, ...) and channel name same as the
        provided notification title if the API is high enough, otherwise
        do nothing.
        .. versionadded:: 1.4.0
        '''

        if SDK_INT < 26:
            return

        manager = autoclass('android.app.NotificationManager')
        channel = autoclass('android.app.NotificationChannel')

        app_channel = channel(
            self._channel_id, name, manager.IMPORTANCE_DEFAULT
        )
        activity.getSystemService(manager).createNotificationChannel(   # <------ HERE
            app_channel
        )
        return app_channel

```

**Comment by avour** [comment]
Just fixed the issue, the problem is you should call activity.getSystemService(Context.NOTIFICATION_SERVICE) instead of activity.getSystemService(manager)

**Comment by SidnetyAtheos** [comment]
Anyone with any solution?
Is there another way to send a notification with kivy that works, am i really in need?
I still get the same error:

`2704 I InputDispatcher: Delivering touch to (18900): action: 0x1, toolType: 1
10-30 11:34:45.137 18900 19050 E zygote  : JNI ERROR (app bug): attempt to pass an instance of java.lang.Class<android.app.NotificationManager> as argument 1 to java.lang.Object android.app.Activity.getSystemService(java.lang.String)
10-30 11:34:45.176 18900 19050 F zygote  : java_vm_ext.cc:534] JNI DETECTED ERROR IN APPLICATION: bad arguments passed to java.lang.Object android.app.Activity.getSystemService(java.lang.String) (see above for details)
10-30 11:34:45.176 18900 19050 F zygote  : java_vm_ext.cc:534]     from int org.libsdl.app.SDLActivity.nativeRunMain(java.lang.String, java.lang.String, java.lang.Object)
`

**Comment by tshirtman** [comment]
https://developer.android.com/reference/android/content/Context#getSystemService(java.lang.Class%3CT%3E)
https://developer.android.com/reference/android/content/Context#getSystemService(java.lang.String)

So there are two getSystemService methods, and one has the signature to accept a class, which is the one we try to use, and one accepts a String, which is the one that gets called here, so it seems like it's a bug in PyJNIus, that calls the wrong version of the method, why on android pie? i don't know, but i'll try to investigate, it's not the first time we have the wrong signature called in jnius, and we've had fixes for it already, maybe there are still holes in the logic.

**Comment by kanekcwu** [comment]
Hi just wondering if we ever find a solution for this. I am using Android Q and seems to have the same problem

**Comment by pakal** [comment]
(As a short term fix, I personnally switched to passing a string instead of a class to getSystemService() ; not in Plyer though, since Plyer seems made for use inside an Activity, and I was in teh context of a Service)
