### ISSUE TITLE
plyer.notification invoke frequency

### ISSUE THREAD

**Issue by g8up** [kivy/plyer#513]
```python
plyer.notification(title="Start", timeout=1)
# do_something(); # less than 1 sec
plyer.notification(title="Finished")
```
(Windows7, Python 3.6)
As I test, one`plyer.notification()` must delay 2 second after the last one, or it will not show out

How to reduce the delay time ?

**Comment by Julian-O** [comment]
Closing as a resolved support question, not a bug report.
