### ISSUE TITLE
[BUG] Audio not working under Python 3.x

### ISSUE THREAD

**Issue by Sirfanas** [kivy/plyer#515]
In audio module, if you try to change file_path it crash under python 3
Reason is here:
https://github.com/kivy/plyer/blob/0b7d8a08108ccb43d751d3fb6fb4a40a21b1ff6c/plyer/facades/audio.py#L91

You are using basestring which is not used anymore in python 3, I think just replace:
```
assert isinstance(location, (basestring, unicode)), \
            'Location must be string or unicode'
```
By:
```
assert isinstance(location, (str, unicode)), \
            'Location must be string or unicode'
```

Should be good

**Comment by Julian-O** [comment]
Closed as fixed
