### ISSUE TITLE
battery.status isCharging always shows false in WINDOWS

### ISSUE THREAD

**Issue by irm19** [kivy/plyer#541]
Hello, 

I have noticed that battery.status['isCharging'] was false in my computer while it was connected. 

The problem is related to line 22 in file https://github.com/kivy/plyer/blob/master/plyer/platforms/win/battery.py

        status["isCharging"] = query["BatteryFlag"] == 8

The problem is that "BatteryFlag" is actually a byte composed of multiple bits, see.. 
https://docs.microsoft.com/en-us/windows/win32/api/winbase/ns-winbase-system_power_status
so if multiple conditions apply, previous value would tend to be false... (in my case it was 'low battery' and 'charging') :-)

So my proposal is to consider somethin like 

         status["isCharging"] = query["BatteryFlag"] & 8 > 0

However, that would still generate issues when BatteryFlag is 255 (Unknown)... so maybe...

         status["isCharging"] = query["BatteryFlag"] !=255 and query["BatteryFlag"] & 8 > 0

There are multiple options to handle this case... :-)

Keep up!!

**Comment by Franccisco** [comment]
Hello! I suggest you to open a pull request with these changes, so they can be tested and eventually merged.

**Comment by irm19** [comment]
Associated pull request #546.
For some unknown reason, it is not passing the "Ubuntu" styles. I assume something else must be wrong in the ubuntu construction, as the file modified is in the Windows side.

**Comment by Zen-CODE** [comment]
Closed by the above merge. Thanks
