### ISSUE TITLE
How to disable mock location (fake gps) in kivy 

### ISSUE THREAD

**Issue by Charanpreet123** [kivy/plyer#555]
Mock location fakes gps and provides wrong coordinates. How to disable mock location using kivy .please provide a solution to disable mock location.

**Comment by Charanpreet123** [comment]
is there anyone who help me in this situation

**Comment by EdwardCoventry** [comment]
Yes! This too caused me a lot of grief before I figured out why I was getting a a set of incorrect gps coordinates alongside my set of correct gps coordinates for every update period.

Bellow is a very basic implementation that I use. I assume that you're asking about android.

In file plyer/platforms/android/gps.py in class AndroidGPS override method _start to be as follow.

```
def _start(self, **kwargs):
        min_time = kwargs.get('minTime')
        min_distance = kwargs.get('minDistance')
        providers = self._location_manager.getProviders(False).toArray()
        for provider in providers:
            #  print all provider names to see if there are any others you'd like to skip
            print('provider:', provider)
            if str(provider) == 'passive':
                print('SKIPPING PASSIVE')
                continue
               #  thus 'passive' location updates are not requested
               #  other providers are requested as normal bellow
            self._location_manager.requestLocationUpdates(
                provider,
                min_time,  # minTime, in milliseconds
                min_distance,  # minDistance, in meters
                self._location_listener,
                Looper.getMainLooper())
```

As you can see this implementation simply skips requesting updates from the 'passive' provider, which for me was giving worse than garbage coordinates.

Some more elegent ways this could be implemented are:
- include a get_available_providers method to wrap self._location_manager.getProviders(False).toArray() in plyer gps
- include an exclude_providers([providers]) function in plyer gps
- include an excluded_providers kwarg in plyer gps.start
- on_location callback kwargs could include the provider name so that unuseful prodivers like 'passive' can be ignored once they're returned.

**Comment by Charanpreet123** [comment]
How to implement this code . Can you please implement in this example
`from kivy.lang import Builder
from plyer import gps
from kivy.app import App
from kivy.properties import StringProperty
from kivy.clock import mainthread
from kivy.utils import platform

kv = '''
BoxLayout:
    orientation: 'vertical'
    Label:
        text: app.gps_location
    Label:
        text: app.gps_status
    BoxLayout:
        size_hint_y: None
        height: '48dp'
        padding: '4dp'
        ToggleButton:
            text: 'Start' if self.state == 'normal' else 'Stop'
            on_state:
                app.start(1000, 0) if self.state == 'down' else \
                app.stop()
'''


class GpsTest(App):

    gps_location = StringProperty()
    gps_status = StringProperty('Click Start to get GPS location updates')

    def request_android_permissions(self):
        """
        Since API 23, Android requires permission to be requested at runtime.
        This function requests permission and handles the response via a
        callback.
        The request will produce a popup if permissions have not already been
        been granted, otherwise it will do nothing.
        """
        from android.permissions import request_permissions, Permission

        def callback(permissions, results):
            """
            Defines the callback to be fired when runtime permission
            has been granted or denied. This is not strictly required,
            but added for the sake of completeness.
            """
            if all([res for res in results]):
                print("callback. All permissions granted.")
            else:
                print("callback. Some permissions refused.")

        request_permissions([Permission.ACCESS_COARSE_LOCATION,
                             Permission.ACCESS_FINE_LOCATION], callback)
        # # To request permissions without a callback, do:
        # request_permissions([Permission.ACCESS_COARSE_LOCATION,
        #                      Permission.ACCESS_FINE_LOCATION])

    def build(self):
        try:
            gps.configure(on_location=self.on_location,
                          on_status=self.on_status)
        except NotImplementedError:
            import traceback
            traceback.print_exc()
            self.gps_status = 'GPS is not implemented for your platform'

        if platform == "android":
            print("gps.py: Android detected. Requesting permissions")
            self.request_android_permissions()

        return Builder.load_string(kv)

    def start(self, minTime, minDistance):
        gps.start(minTime, minDistance)

    def stop(self):
        gps.stop()

    @mainthread
    def on_location(self, **kwargs):
        self.gps_location = '\n'.join([
            '{}={}'.format(k, v) for k, v in kwargs.items()])

    @mainthread
    def on_status(self, stype, status):
        self.gps_status = 'type={}\n{}'.format(stype, status)

    def on_pause(self):
        gps.stop()
        return True

    def on_resume(self):
        gps.start(1000, 0)
        pass


if __name__ == '__main__':
    GpsTest().run()`

**Comment by Charanpreet123** [comment]
How can i implement ths code in my code . Can you please implement this code im an example . 

``from kivy.lang import Builder
from plyer import gps
from kivy.app import App
from kivy.properties import StringProperty
from kivy.clock import mainthread
from kivy.utils import platform

kv = '''
BoxLayout:
    orientation: 'vertical'
    Label:
        text: app.gps_location
    Label:
        text: app.gps_status
    BoxLayout:
        size_hint_y: None
        height: '48dp'
        padding: '4dp'
        ToggleButton:
            text: 'Start' if self.state == 'normal' else 'Stop'
            on_state:
                app.start(1000, 0) if self.state == 'down' else \
                app.stop()
'''


class GpsTest(App):

    gps_location = StringProperty()
    gps_status = StringProperty('Click Start to get GPS location updates')

    def request_android_permissions(self):
        """
        Since API 23, Android requires permission to be requested at runtime.
        This function requests permission and handles the response via a
        callback.
        The request will produce a popup if permissions have not already been
        been granted, otherwise it will do nothing.
        """
        from android.permissions import request_permissions, Permission

        def callback(permissions, results):
            """
            Defines the callback to be fired when runtime permission
            has been granted or denied. This is not strictly required,
            but added for the sake of completeness.
            """
            if all([res for res in results]):
                print("callback. All permissions granted.")
            else:
                print("callback. Some permissions refused.")

        request_permissions([Permission.ACCESS_COARSE_LOCATION,
                             Permission.ACCESS_FINE_LOCATION], callback)
        # # To request permissions without a callback, do:
        # request_permissions([Permission.ACCESS_COARSE_LOCATION,
        #                      Permission.ACCESS_FINE_LOCATION])

    def build(self):
        try:
            gps.configure(on_location=self.on_location,
                          on_status=self.on_status)
        except NotImplementedError:
            import traceback
            traceback.print_exc()
            self.gps_status = 'GPS is not implemented for your platform'

        if platform == "android":
            print("gps.py: Android detected. Requesting permissions")
            self.request_android_permissions()

        return Builder.load_string(kv)

    def start(self, minTime, minDistance):
        gps.start(minTime, minDistance)

    def stop(self):
        gps.stop()

    @mainthread
    def on_location(self, **kwargs):
        self.gps_location = '\n'.join([
            '{}={}'.format(k, v) for k, v in kwargs.items()])

    @mainthread
    def on_status(self, stype, status):
        self.gps_status = 'type={}\n{}'.format(stype, status)

    def on_pause(self):
        gps.stop()
        return True

    def on_resume(self):
        gps.start(1000, 0)
        pass


if __name__ == '__main__':
    GpsTest().run()``

**Comment by Charanpreet123** [comment]
hii, 
i overide _start method In file plyer/platforms/android/gps.py in class AndroidGPS
but nothing hapens , result is same as wrong coordinates.

**Comment by EdwardCoventry** [comment]
Okay you could try this. In plyer/platforms/android/gps.py override the method onLocationChanged to be as follows.
```
@java_method('(Landroid/location/Location;)V')
def onLocationChanged(self, location):
    self.root.on_location(
        lat=location.getLatitude(),
        lon=location.getLongitude(),
        speed=location.getSpeed(),
        bearing=location.getBearing(),
        altitude=location.getAltitude(),
        accuracy=location.getAccuracy(),
        provider=location.getProvider(),
        mock=location.isFromMockProvider())
```
Kwargs for provider and mock are added. These values will display in the plyer gps example without you having to edit the example. Then in your on_location function you could just ignore mock location updates by adding something like `if kwargs.get(mock): return` to your on_location method.

**Comment by Charanpreet123** [comment]
i change both functions but nothing works 
thats my code :
`
    @java_method('(Landroid/location/Location;)V')
    def onLocationChanged(self, location):
        self.root.on_location
            lat=location.getLatitude(),
            lon=location.getLongitude(),
            speed=location.getSpeed(),
            bearing=location.getBearing(),
            altitude=location.getAltitude(),
            accuracy=location.getAccuracy(),
            provider=location.getProvider(),
            mock=location.isFromMockProvider())
`

`def _start(self, **kwargs):
        min_time = kwargs.get('minTime')
        min_distance = kwargs.get('minDistance')
        available_providers = self._location_manager.getProviders(False).toArray()
        #  the providers i get are called ['passive', 'gps', 'network']
        #  i don't know if theyre the same on all devices
        #  for me the garbage provider is called 'passive'
        excluded_providers = ['passive']
        providers = [provider for provider in available_providers if provider not in excluded_providers]
        for provider in providers:
            self._location_manager.requestLocationUpdates(
                provider,
                min_time,  # minTime, in milliseconds
                min_distance,  # minDistance, in meters
                self._location_listener,
                Looper.getMainLooper())
`

but no result ,My logcat : 

`04-15 23:04:28.748 30339 30363 I python  : ['lat=30.3880285', 'lon=76.7706216', 'speed=0.0', 'bearing=0.0', 'altitude=0.0', 'accuracy=1299.9990234375']
04-15 23:04:28.748 30339 30363 I python  : {'lat': 30.3880285, 'lon': 76.7706216, 'speed': 0.0, 'bearing': 0.0, 'altitude': 0.0, 'accuracy': 1299.9990234375}
04-15 23:04:28.748 30339 30363 I python  : ['lat=30.3880285', 'lon=76.7706216', 'speed=0.0', 'bearing=0.0', 'altitude=0.0', 'accuracy=1299.9990234375']
04-15 23:04:30.141 30339 30363 I python  : {'lat': 30.3880285, 'lon': 76.7706216, 'speed': 0.0, 'bearing': 0.0, 'altitude': 0.0, 'accuracy': 1299.9990234375}
04-15 23:04:30.142 30339 30363 I python  : ['lat=30.3880285', 'lon=76.7706216', 'speed=0.0', 'bearing=0.0', 'altitude=0.0', 'accuracy=1299.9990234375']
04-15 23:04:30.154 30339 30363 I python  : {'lat': 30.3880285, 'lon': 76.7706216, 'speed': 0.0, 'bearing': 0.0, 'altitude': 0.0, 'accuracy': 1299.9990234375}
04-15 23:04:30.154 30339 30363 I python  : ['lat=30.3880285', 'lon=76.7706216', 'speed=0.0', 'bearing=0.0', 'altitude=0.0', 'accuracy=1299.9990234375'] `

my python code : 
` @mainthread
    def print_locations(self,**kwargs):
        self.gps_location = ['{}={}'.format(k, v) for k, v in kwargs.items()]
        print(self.gps_location)
`

**Comment by Charanpreet123** [comment]
` @mainthread
    def print_locations(self,**kwargs):
        self.gps_location = ['{}={}'.format(k, v) for k, v in kwargs.items()]
        print(self.gps_location)
`

**Comment by Charanpreet123** [comment]
>  @mainthread
    def print_locations(self,**kwargs):
        self.gps_location = ['{}={}'.format(k, v) for k, v in kwargs.items()]
        print(self.gps_location)

**Comment by Charanpreet123** [comment]
i think problem is in gps.pyc file , which did nt updated , 
hence did not show results .how to compile again this file .or there is any other solution ?

**Comment by Charanpreet123** [comment]
@EdwardCoventry  thanks for your help, now its working fine .
