### ISSUE TITLE
Notimplemented Error with plyer text to speech

### ISSUE THREAD

**Issue by SivaramNalliboyana** [kivy/plyer#560]
I am on windows and i have the plyer module installed

This is my code:
from plyer import tts
tts.speak(message='hello world')

I have a simple code, but why do I get a notimplementederror() with plyer.
Am I doing something wrong

**Comment by Franccisco** [comment]
According to these lines:

https://github.com/kivy/plyer/blob/11b6b4b1565b04a6c7919ca8b3ed0aed86784915/plyer/platforms/win/tts.py#L14-L15

You should have a espeak.exe file, otherwise it returns the
`NotImplementedError`.

**Comment by EdwardCoventry** [comment]
For me I also had to add C:\Program Files (x86)\eSpeak\command_line to my path
