### ISSUE TITLE
Plyer notification when app is not running

### ISSUE THREAD

**Issue by SivaramNalliboyana** [kivy/plyer#564]
Hi, everyone. I have made a simple notification app with kivy. And it is working. Whenever I click the button, I am getting the notification.
But my problem, how would it be in android, when the app is not running. When the device is off or when I close the app. I should still get the notification right?.
But how is it possible

**Comment by Python3-8** [comment]
Yeah, I've been wanting to do this too. Apps like Google Hangouts, Gmail, WhatsApp, Pidgin, MEGAsync, Adium, and more run in the background. I didn't know how to do it. Thanks @mcroni.
