### ISSUE TITLE
bluetooth for Android

### ISSUE THREAD

**Issue by ffrige** [kivy/plyer#571]
Hello, I am using Kivy to develop an application for Android. I need to access a remote device via Bluetooth and transmit/receive data. I saw that the plyer bluetooth module only offers the info function to read the actual status, but there are no functions to send/receive data. How does that part work? Do I need to import other libraries? Or are the communication functions in plyer still being developed?
Thanks!

**Comment by Franccisco** [comment]
Hello

As you can see, the current Bluetooth implementation is very limited. If
you want to implement some functions by yourself, you can use
[pyjnius][1] to call Java classes.

[1]: https://github.com/kivy/pyjnius

Here is some documentation I found about using Bluetooth in Android:

https://developer.android.com/guide/topics/connectivity/bluetooth

Also, there is a (now inactive) effort to add more functionality to the
bluetooth facade for android in #184.

By the way, if you get to make it work, contributions are welcome!

**Comment by ffrige** [comment]
I see, thank you. I will look into pyjnius and see if I can get it to work there.
