### ISSUE TITLE
tts is not working

### ISSUE THREAD

**Issue by akchhayalok** [kivy/plyer#572]
Hi Team

I wrote python3.6 script for tts in an ubuntu system with vs code. When i am running it's throwing me NotImplementedError. I have installed plyer module as battery is working in ubuntu but not tts. 
```
def speak(self,text_to_read):
        tts.speak(text_to_read)
``` 
I am getting this error
```
File "/home/Users/.local/lib/python3.6/site-packages/plyer/facades/tts.py", line 39, in _speak
     raise NotImplementedError()
 NotImplementedError
```

**Comment by Franccisco** [comment]
Hi!

According to these lines:

https://github.com/kivy/plyer/blob/dec02d7802ba83353395a44dae5f1b63c01c6be2/plyer/platforms/linux/tts.py#L20-L25

You neeed `espeak` or `flite` installed first.

**Comment by akchhayalok** [comment]
Thanks @Franccisco It worked.
