### ISSUE TITLE
STT start and stop immediately

### ISSUE THREAD

**Issue by Marouxet** [kivy/plyer#573]
Hello! 

I am starting to test the stt app with plyer in android. I've just download the example (https://github.com/kivy/plyer/blob/master/examples/speech2text/main.py) and compiled it with buildozer. App starts but when I click on "start button" (stt.start() method) i listen the "bip" sound for starting to listening and the "bip-bup" sound for stop listening at the same time. When I check the object using de logcat I get always empty list for partial results and for results and also I get a False status in "listeting" variable. 

I have checked the permissions (record audio and internet), they are ok. I added a rutine for ask for permission in context and  permissions are ok in settings. I also change the "preffer ofline"option, and I also tried  to change the keyboard in settings (from sansumg to gboard). 

I see the program enter in the schedule routine but i add (print(stt.partial_results())) and it is empty [].

Any ideas what is going on? 

Thanks!!!

**Comment by mrever** [comment]
Any progress on this?  I would also like to get the speech2text working.  It doesn't play any sounds for me, but it starts up and when I click "Start Listening" it flashes "Stop" and immediately resets.  I've also made sure it has microphone etc. permissions enabled.

Thanks

**Comment by furmanlukasz** [comment]
Having the same issue. Any luck?

**Comment by will702** [comment]
yeah, I have the same issue too can somebody help me with that issue

**Comment by nandamtejas** [comment]
Hello everyone 
I am working on Kivy app which includes Bluetooth and stt. Before it worked well but the same app is not working after I updated my Android phone to newer version.
Isn't that the newer version of Android doesn't support the stt?
