### ISSUE TITLE
How do I set the app orientation with Plyer?

### ISSUE THREAD

**Issue by Python3-8** [kivy/plyer#580]
I'm creating this game with KivyMD and I used Plyer for vibrations, notifications, and to set the app orientation. Everything works well on Android, but on iOS nothing works. I can't vibrate the device, I can't display notifications, and I can't set the app orientation. Is there any iOS permission that lets an app vibrate the device? If so, may I please know what it is? And can someone please tell me how I can set the app orientation or display notifications on iOS?

**Comment by surak** [comment]
Did you find the solution for this one?

**Comment by misl6** [comment]
Hi @Python3-8 and @surak !

orientation: NOT supported on iOS
notifications: NOT supported on iOS
vibrator: A limited set of features are supported. Did you added AudioToolbox framework to your App? See: https://github.com/kivy/plyer/blob/master/plyer/platforms/ios/vibrator.py

See: https://github.com/kivy/plyer#supported-apis

Closing as support, feel free to open a new feature request for the missing features :)
