### ISSUE TITLE
How do I get notifications to persist in plyer on windows 10?

### ISSUE THREAD

**Issue by Robby-Sodhi** [kivy/plyer#599]
For example currently when I call a notification like this:
from plyer import notification
notification.notify(title="Test",message="test2",timeout=None)
the notification gets deleted after a set amount of time (Doesn't stay in the windows notification center)
How can I make the notifications persist?

**Comment by Robstersgaming** [comment]
My mistake specyfying no timeout lets it persist :P
notification.notify(title="Test",message="test2")

**Comment by Robstersgaming** [comment]
Even taking out timeout=None the notification continues to disappear after the script finishes.

**Comment by Ratulhasan14789** [comment]
tested such situation but it didn't disappear (on windows 10 os) timeout doesn't affect how long the notification lasts in this os, whats your OS (plyer is badly os biased but tries to be least os dependent in the front)

**Comment by Robstersgaming** [comment]
> tested such situation but it didn't disappear (on windows 10 os) timeout doesn't affect how long the notification lasts in this os, whats your OS (plyer is badly os biased but tries to be least os dependent in the front)

I am on Windows 10. (If anyone else is interested I ended up using a library called winnotify)
