### ISSUE TITLE
plyer's last release was ~2 years ago, the number of open PRs is absurd, and the last meaningful commit was months ago

### ISSUE THREAD

**Issue by leycec** [kivy/plyer#674]
plyer is functionally dead for all intents and purposes. Active development all but [ground to a halt last November](https://github.com/kivy/plyer/commits/master) despite a [ludicrous number of passing open pull requests (PRs)](https://github.com/kivy/plyer/pulls) and [growing laundry list of critical open issues](https://github.com/kivy/plyer/issues). The core idea is sound; the development effort is not.

Ideally, existing maintainers would grant GitHub **Collaborator** status to one or more users with a proven track record of multiple previously accepted PRs. Pragmatically, that's unlikely to happen.

Are there valid alternatives to plyer with similar scope and feature set still in active development? I pray to Octocat for a saner dev cycle in competing projects. :pray: :octocat: :pray:

**Comment by RobertFlatt** [comment]
Indeed, it looks like abandonware.

It would help it invalid checks were removed from this chart https://github.com/kivy/plyer#supported-apis Plyer now is a Potemkin Village https://en.wikipedia.org/wiki/Potemkin_village no way to know if there really is something behind the facade.

To be fair its an impossible support task, you have to be fluent and current on all platforms so other people don't have to be. Very appealing to everybody else, but the waves are continually washing your sand castle off the beach.

**Comment by Zen-CODE** [comment]
Noted @leycec  . Although not entirely accurate, the point is valid. But it's not "abandoned", it's just lacks the manpower for it to get the love it deserves. And yes, we do look for regular contributors to try and give them approval power, but they often move on. Most often people just fix the issue that's relevant to them and move on. Nothing wrong there, at least they give back, but it does mean big efforts (like plyer) seldom get constant attention.

Either way, this is not an action-able issue report, so I'm going to close this ticket. But thanks, would be great if you could help out in any way here.....

Cheers
