### ISSUE TITLE
AttributeError: 'function' object has no attribute 'dialcall'

### ISSUE THREAD

**Issue by KINGMOHIT** [kivy/plyer#682]
my code is 100% same as yours just added 20 more things which doesn't have anything to do with call

**Comment by Julian-O** [comment]
This isn't enough information to determine what the problem might be.

Closing as Can't Repro.

There is a mailing list and a Discord channel to support Kivy users debugging their own systems, which should be able to help. They are linked in the [ReadMe](https://github.com/kivy/buildozer#support).
