### ISSUE TITLE
Loss of dependencies on OSX/Windows

### ISSUE THREAD

**Issue by Neizvestnyj** [kivy/plyer#686]
The user needs to be explicitly told that `PyOBJus` for **MacOS** is missing, not just a `NotImplementedError` error. `win32com`, which is part of `pypiwin32`, often fails on **Windows**, I fix it using _conda_.

**Comment by Julian-O** [comment]
This issue contains multiple problems, but not enough detail to act on either.

#779  should address the PyOBJus issue.
The second issue but may be fixed by #737.

Closing as presumed duplicate.

If this is in error, please give more background about the specific problem.
