### ISSUE TITLE
plyer filechooser not working 

### ISSUE THREAD

**Issue by Sahil-pixel** [kivy/plyer#696]
OS: kubuntu 22.04
python 3.10
kivy 2.1.0
log

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/.local/lib/python3.10/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx.

**Comment by misl6** [comment]
HI @Sahil-pixel !

Can you post a full log?

**Comment by Julian-O** [comment]
No reply after 3 months. Closing as Can't Repro
