### ISSUE TITLE
unformatted content on pypi page

### ISSUE THREAD

**Issue by totallynotadi** [kivy/plyer#698]
I've been concerned about the pypi page for plyer. The markdown is not rendered properly and the license shows up at the top unlike in that in the readme. Everything renderes properly on the github readme but not on the pypi page. there's also no way to read a short, well formatted intorduction for people discovering the pypi page first since it doesnt lead to the github repo. A shorter, more comprehensive intro is better to be on the front pages imo as opposed to the readthedocs, but pypi messes up formatting.

![this](https://pypi.org/project/plyer/) is how the page looks. There's a couple of issues with it - 
* license shows up unnecessarily.
* markdown is completely disregarded altogether.

it would be nice to see a sweet pypi page for plyer but i have no idea what's causing these issues
my best guess is regarding the `package_data` parameter from `setup.py` combined with the `manifest.in` file causing pypi to render things this way.

the following are the contents from `setup.py`
```
setup(
    name='plyer',
    version=plyer.__version__,
    description='Platform-independent wrapper for platform-dependent APIs',
    long_description=README + u"\n\n" + CHANGELOG + u"\n\n",
    long_description_content_type='text/markdown',
    author='Kivy team',
    author_email='mat@kivy.org',
    url='https://plyer.readthedocs.org/en/latest/',
    packages=PACKAGES,
    package_data={'': ['LICENSE', 'README.md']},
    package_dir={'plyer': 'plyer'},
    include_package_data=True,
    license=open(join(CURDIR, 'LICENSE')).read(),
    zip_safe=False,
    classifiers=[
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
    ]
)
```

and `manifest.in` just contains

```
include *README.rst *LICENSE
include *CHANGELOG.md
```

appreciate help for ideas to resolve this issue, thanks

**Comment by Julian-O** [comment]
Is fixed now, perhaps by the PR associated with #701.

Closing as complete.
