### ISSUE TITLE
plyer notification android api 31 error

### ISSUE THREAD

**Issue by wlyapps** [kivy/plyer#702]
android api 31 error!

plyer notification has the following error on android api 31:

JVM exception occurred: org.testeapps.controllapp:
Targeting S+ (version 31 and above) requires that one
of FLAG_IMMUTABLE or FLAG_MUTABLE be specified
when creating a Pendingintent. Strongly consider using
FLAG_IMMUTABLE, only use FLAG_MUTABLE if some

functionality depends on the Pendingintent being
mutable, e.g. if it needs to be used with inline replies or
bubbles. java.lang.IllegalArgumentException

**Comment by LazzaAU** [comment]
i have the same issue and guessing this is the cause of not getting notification when i run the app on android. Was there any thoughts on where i'd need to add the flag's ? or is that something that needs done internally of plyer ?

**Comment by LazzaAU** [comment]
Is there any plans to fixing this ? I can't set my API level to anything above 30 or this error kicks in. Google tells me i cant upload a aab file to the play store if the API is under 31. So i'm kinda stuck on the fence.

Other than setting up push notifications any suggestions to work around this ?

**Comment by Zahrafathi1234** [comment]
I have the same issue. Did you find a solution for it? I asked my question here.  Can the problem be solved?
https://stackoverflow.com/questions/75532341/flag-immutable-or-flag-mutable-in-notification-kivy-for-android
I am a new Kivy user and I don't know where the problem is.

**Comment by SomberNight** [comment]
feel free to test with https://github.com/kivy/plyer/pull/756 - that works for me

**Comment by seba-plpl** [comment]
hi, i tried to test it using https://github.com/HyTurtle/plyer/archive/master.zip in requirements but no luck, i have this issue: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

please tell me, how to test it?

**Comment by SomberNight** [comment]
That fork looks too old. Try using kivy/plyer.

**Comment by rdb** [comment]
It looks like there has not been a Plyer release since this issue was fixed in 2023, is it possible to push a new release to PyPI? This is currently a blocker for the ability to use notifications on Android since it's no longer possible to upload new apps targeting SDK level 30.
