### ISSUE TITLE
Dynamic Permission Request on Android for Camera

### ISSUE THREAD

**Issue by darahsten** [kivy/plyer#703]
Since Marshmallow some permissions such as Camera are denied by default. The user has to go to the settings app and manually allow permissions.

The alternative, which is more user friendly is to dynamically ask for this permission.

Plyer does not seem to have this functionality to dynamically ask for this permission on android.

Without the explicit granting of permission (either) on the users initiative GoTo Settings> Apps > [The APP]> Permissions.
Or the dynamic permission request, when the user needs to use the Camera.

The App will throw JVM exception occurred: Fail to connect to camera service java.lang.RuntimeException

**Comment by RobertFlatt** [comment]
It is an Android constraint that only one call to permissions() may be made in a given timestep. 
A given api cannot tell if another api has called permissions in that timestep.

Therefore is has to be the programmer's responsibility to manage run time permissions.
Its easy 
https://github.com/Android-for-Python/Android-for-Python-Users#user-permissions

**Comment by darahsten** [comment]
Thanks, let me read through.

**Comment by darahsten** [comment]
The comment was helpful.
