### ISSUE TITLE
iOS: filechooser - multiple files selection is not working

### ISSUE THREAD

**Issue by einfall** [kivy/plyer#708]
iOS: filechooser - multiple files selection is not working.

Bounty: 
https://app.bountysource.com/issues/111632557-ios-filechooser-multiple-files-selection-is-not-working

**Comment by mbrockman1** [comment]
I have been using PythonSwiftLink for this if you are interested.

**Comment by einfall** [comment]
> I have fixed this and some other related issues on filechooser.

where ?

**Comment by einfall** [comment]
i use this code and only can select one file

filechooser.open_file(on_selection=self.gotFiles, multiple=True)

on ios 16.1

**Comment by einfall** [comment]
with UIImagePickerController you can't select multiple file.

Maybe PHPickerViewController is the better solution ?

**Comment by einfall** [comment]
Here is the Test Code:

from kivy.app import App
from kivy.lang import Builder
from plyer import filechooser

from kivy.core.window import Window
Window.size = (300, 550)

KV = '''
Screen:

    Button:
        id: image_picker
        text: "Select Images"
        on_release: app.open_image_picker()

'''

class Test(App):

    def build(self):
        self.root = Builder.load_string(KV)

    def open_image_picker(self):
        filechooser.open_file(on_selection=self.callback_images, multiple=True)

    def callback_images(self, files):
        if files:
            for file_path in files:
                print(file_path)


Test().run()

**Comment by Azag3077** [comment]
@einfall sorry bro, I was referring to Android. Didn't see the IOS in your post.

**Comment by einfall** [comment]
i am working on a solution, i can select mutiple Images but after clicking on ADD nothing happend (see Xcode Console Log and Video).
Maybe someone can help :-)

from kivy.app import App
from kivy.lang import Builder

from pyobjus import autoclass, protocol
from pyobjus.dylib_manager import load_framework, INCLUDE

load_framework('/System/Library/Frameworks/PhotosUI.framework')
load_framework('/System/Library/Frameworks/Photos.framework')
load_framework('/System/Library/Frameworks/AssetsLibrary.framework')
load_framework('/System/Library/Frameworks/Foundation.framework')
load_framework('/System/Library/Frameworks/UIKit.framework')

from kivy.core.window import Window
Window.size = (300, 550)

KV = '''
Screen:

    Button:
        id: image_picker
        text: "Select Images"
        on_release: app.open_image_picker()
'''

class Test(App):

    def build(self):
        self.root = Builder.load_string(KV)

    def open_image_picker(self):
        conf = autoclass("PHPickerConfiguration")
        config = conf.alloc().init()
        config.selectionLimit = 0
                
        PHPickerViewController = autoclass("PHPickerViewController")
        ppvc = PHPickerViewController.alloc().initWithConfiguration_(config)

        UIApplication = autoclass('UIApplication')
        vc = UIApplication.sharedApplication().keyWindow.rootViewController()
        vc.presentViewController_animated_completion_(ppvc, True, None)

    @protocol('PHPickerViewControllerDelegate')
    def didFinishPicking(self, image_picker, frozen_dict):
        image_picker.dismissViewControllerAnimated_completion_(True, None)
        print(image_picker)

Test().run()



https://user-images.githubusercontent.com/3679001/207412153-96293062-a51e-420e-a574-5f34a9bc4d00.mp4

Xcode Console Log:
022-12-13 19:08:42.502462+0100 imagepicker[9230:4292690] [Picker] PHPickerViewControllerDelegate doesn't respond to picker:didFinishPicking:
2022-12-13 19:08:44.717942+0100 imagepicker[9230:4292690] [Picker] PHPickerViewControllerDelegate doesn't respond to picker:didFinishPicking:

**Comment by einfall** [comment]
I added a Bounty 150 $
For multi file selection in plyer/ios like phpicker

https://app.bountysource.com/issues/111632557-ios-filechooser-multiple-files-selection-is-not-working

**Comment by einfall** [comment]
no one can help :-( ?

**Comment by mbrockman1** [comment]
I would try to talk with PythonSwiftLink creator on discord. It essentially allows to write a python wrapper for swift. It is very easy to use.

**Comment by einfall** [comment]
thx
