### ISSUE TITLE
Read TEXT_AUTO_CAPS setting

### ISSUE THREAD

**Issue by antorix** [kivy/plyer#741]
Maybe Plyer can implement the possibility to read one more Android setting from Kivy: TEXT_AUTO_CAPS (https://developer.android.com/reference/android/provider/Settings.System#TEXT_AUTO_CAPS). I need to get this setting in my app to control the text input, but have not yet found any way to do so.

**Comment by misl6** [comment]
Hi @antorix !
You can use `pyjnius` to read this setting.

BTW, when using the `TextInput` in `text` mode, that should be the normal behavior.

**Comment by antorix** [comment]
> You can use pyjnius to read this setting.

Can you show how?

> BTW, when using the TextInput in text mode, that should be the normal behavior.

Are you sure? I and other users I know see that TextInput ignores this setting in any mode. That's exactly the reason why I asked this question.
