### ISSUE TITLE
USSD command (new feature)

### ISSUE THREAD

**Issue by depau** [kivy/plyer#76]
I propose the addition of the USSD feature.
For those who don't know what an USSD command is: it's a particular kind of network request where you type in a command (e.g. _123#, *123_45#, _123_, etc...) and the network responds with some text (e.g. credit information). Sometimes the network keeps the session open waiting for the user to respond back: in that case you can either cancel or respond.
The facade should provide three methods: initiate (accepts a string with the command, returns network's response), respond (accepts a string with the response, returns network's response), cancel, and some way to see if a session is open or not.
See this for more details: http://www.freedesktop.org/software/ModemManager/api/latest/gdbus-org.freedesktop.ModemManager1.Modem.Modem3gpp.Ussd.html
##

**Comment by Julian-O** [comment]
After 9 years, it appears the OP is happy with the status quo, and no-one else is clamouring for the change.

Closing as stale. 

If you still want more from this feature, please let us know.
