### ISSUE TITLE
Feature Request: Alarms

### ISSUE THREAD

**Issue by brousch** [kivy/plyer#8]
An API for setting an alarm and triggering an event sometime in the future.

Android: AlarmManager
Linux: cron
OSX: cron
Windows: Task Scheduler
##

**Comment by dessant** [comment]
There has been a chat about a schedule facade, it is not evident how it should really work across platforms or if it fits in plyer.
https://botbot.me/freenode/kivy-dev/2015-05-05/?msg=38384258&page=1
