### ISSUE TITLE
Re-opening playsound facade

### ISSUE THREAD

**Issue by trivedigaurav** [kivy/plyer#81]
I had closed the playsound pr (https://github.com/kivy/plyer/pull/65) without merging giving a reason that the user was better off including the external libs themselves. For example, if the app developer is using Kivy as the main framework to build their apps, it already has libs to play sounds.
##

**Comment by eadmaster** [comment]
isn't this feature already provided by `audio`?

e.g.
````
		from plyer import audio
		audio.file_path = filepath
		audio.play()
````

**Comment by Julian-O** [comment]
There doesn't appear to be much further interest in this topic.

Closing.
