### ISSUE TITLE
Feature request: Accelerometer on Linux (computers)

### ISSUE THREAD

**Issue by Depau** [kivy/plyer#9]
There's no way to detect if it is a joystick or an accelerometer other than reading the name, but AFAIK on Ubuntu accelerometers and some joysticks follow this glob:
/sys/devices/platform/*/position
The position file contains the value of the axes. I'm pretty sure though that there's a better way to read it than reading the position file. I think jstest-gtk is written in python.
##

**Comment by KeyWeeUsr** [comment]
Ref
* example: https://github.com/kivy/plyer/issues/19
* MacOS: https://github.com/kivy/plyer/issues/29
* GNU/Linux: https://github.com/kivy/plyer/pull/68, https://github.com/kivy/plyer/pull/51
* Windows (not yet): https://github.com/kivy/plyer/issues/33
